### ISSUE TITLE
Баги с `locomotive-scroll`

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/drum-in#100]
### Описание бага

- [x] В мобильном виде "белый квадрат"
- [ ] В мобильном виде реализовать скролл программы с новой "прозрачной картинкой"
- [ ] Слайдер не скроллится до конца

### Воспроизведение

Актуальный релиз. Страницы **polyrhythmic-keys**, **feeling-of-time**, **fifth-dimension**, **seventh-heaven**, **connacol** с шириной экрана менее 640px.

### Ожидаемое поведение

- В мобильном виде пофикшен "белый квадрат"
- Слайдер скроллится до конца прежде чем идти далее

### Материалы

<details>
<summary>Баг в мобильном виде:</summary>

<img width="667" alt="Screenshot 2023-05-10 at 09 44 35" src="https://github.com/torin-asakura/drum-in/assets/44067768/1d8e9b45-cd43-4664-88a2-a33bfcab2ff1">

</details>

<details>
<summary>Картинка программы в мобильном виде с непрозрачным фоном:</summary>

<img width="708" alt="image" src="https://github.com/torin-asakura/drum-in/assets/44067768/c3f90296-fbf8-4882-8083-ed539564eadd">

</details>

<details>
<summary>Горизонтальная прокрутка не до конца</summary>

<img width="965" alt="Screenshot 2023-05-10 at 09 45 46" src="https://github.com/torin-asakura/drum-in/assets/44067768/92cee7e3-6505-4045-a7a5-2a97e1261253">

</details>

### Данные окружения

- macOS@13.3.1(a)
- Safari@16.4 (18615.1.26.110.1)

**Comment by Nelfimov** [comment]
> - [ ] В мобильном виде "белый квадрат"

Баг встречается на всех страницах где есть roadmap в мобильных версиях (напр. **ContentMobileCourse** в **landing-program-polyrhythmic-keys**). При ширине viewport менее 640px к элементу 
```
        <Box
          height={[200, 300, 0]}
          width='100%'
          flexShrink={0}
          backgroundColor='background.smokyWhite'
        />
```

добавляется атрибут ``transform=matrix3d...`` с негативным смещением вверх на высоту этого элемента. Для элемента выше - 200px и 300px соответственно.

Потенциально причина - выполнение этой функции в **locomotive-scroll**

```
{
      key: "transform",
      value: function transform(element, x, y, delay) {
        var transform;

        if (!delay) {
          transform = "matrix3d(1,0,0.00,0,0.00,1,0.00,0,0,0,1,0,".concat(x, ",").concat(y, ",0,1)");
        } else {
          var start = getTranslate(element);
          var lerpX = lerp(start.x, x, delay);
          var lerpY = lerp(start.y, y, delay);
          transform = "matrix3d(1,0,0.00,0,0.00,1,0.00,0,0,0,1,0,".concat(lerpX, ",").concat(lerpY, ",0,1)");
        }

        element.style.webkitTransform = transform;
        element.style.msTransform = transform;
        element.style.transform = transform;
      }
}

```

Необходимо копать дальше.

**Comment by eshevlyakova** [comment]
@Nelfimov 

> подскажи, откуда взят fork locomotive-scroll?

Ну в проекте в папке forks инициализируются нужные компоненты и хуки, чтобы каждый раз это не делать (на каждой странице). Делала по примеру других наших проектов ([например](https://github.com/torin-asakura/misik/tree/master/forks/react-locomotive-scroll))

**Comment by Nelfimov** [comment]
Подключение `@types/locomotive-scroll` указывает на ошибки в options:
```
<LocomotiveScrollProvider
        options={{
          smooth: true,
          smartphone: {
            smooth: true,
            smartphone: {
              smooth: true,
            },
            tablet: {
              smooth: true,
            },
          },
        }}
        containerRef={containerRef}
        watch={[]}
      >
```
Вложенность в smartphone ошибочна, необходимо на верхнем уровне указывать:
```
<LocomotiveScrollProvider
        options={{
          smooth: true,
          smartphone: {
            smooth: true,
          },
          tablet: {
            smooth: true,
          },
        }}
        containerRef={containerRef}
        watch={[]}
      >
```
Так же типизация ссылается на breakpoint в tablet. Дефолт - 1024px.

**Comment by tverikinlv** [comment]
> - [ ] В мобильном виде "белый квадрат"

**1.** При запуске проекта локально при переходе на любую из страниц курсов появлеятся ошибка

 
![Снимок 1](https://github.com/torin-asakura/drum-in/assets/65893714/08276370-7fee-4c6d-8bab-8477f9c7b0da)

**2.** "Белый квардарт" - это вложенный в обертку элемент: 


```
        <Box 
          height={[200, 300, 0]} 
          width='100%'
          flexShrink={0}
          backgroundColor='background.smokyWhite'
        />
```

Сама обертка-родитель: 

```
    <Box
        data-scroll
        data-scroll-sticky
        data-scroll-target='#scroll-mobile'
        width='100%'
        position='absolute'
        top={0}
        left={0}
        zIndex={1}
      >
```
 
При скоролле вниз, происходит премещение вложенного элемента по вертикали при помощи CSS-свойства  `transform: matrix3d()`

**3.** При ширине viewport менее 640px у CSS-свойства  `transform: matrix3d() ` обертки-родителя перестаёт изменяться значение, которое отвечает за перемещение, устанавливается сразу на высоту вложенного элемента (-200px) и более не вычисляется динамически.
 
![Снимок 2](https://github.com/torin-asakura/drum-in/assets/65893714/647dcb7c-b22e-4b7b-ade7-b2dfd745fea8)

Если посмотреть на этот же элемент в инспекторе при ширине viewport более 640px, то можно увидеть, что вычиления производятся и передаются в свойство

![Снимок 4](https://github.com/torin-asakura/drum-in/assets/65893714/a3964f08-78ab-4dc6-aaab-83ce0433ec14)


Из этого возможно сделать вывод, что прчина выполнения скорее не в функции **transform**, которая является частью **locomotive-scroll**, а в вычислении и передаче значений который происходят при скролле конкретно на ширине viewport менее 640px.

**Comment by tverikinlv** [comment]
**1.** При ширине viewport менее 640px, поведение "белого квадрата" никак не зависит от ширины и высоты родительских элементов

**2.** При загрузке сразу на ширину viewport менее 640px родительскому элементу не присваевается класс "is-inveiw", который должен присваиваться элементам с атрибутом data-scroll="true"

**Comment by kalininatonya** [comment]
Исправила ошибку с "белым квадратом".
