### ISSUE TITLE
Запуск проекта

### ISSUE THREAD

**Issue by Tsukimono13** [torin-asakura/drum-in#111]
### Скоуп

Запуск проекта

### Описание

Не могу развернуть приложение на localhost:3000. ОС - Ubuntu. Node.js -  v18.16.1, устанавливала через Ubuntu Software.

### Воспроизведение

Последовательность моих действий: 
1. Открываю проект
2. Добавляю завсимости yarn install
3. Прописываю команды 
docker compose run yarn
docker compose run landing-build
docker compose run landing-start

Команды проходят, порт 3000 начинает прослушиваться.

4. Запускаю команду yarn && yarn workspace @landing/renderer-entrypoint dev

Если открыть localhost:3000, то

"Не удается получить доступ к сайту. Сайт localhost не позволяет установить соединение.
Попробуйте сделать следующее:

Проверьте подключение к Интернету.
[Проверьте настройки прокси-сервера и брандмауэра](chrome-error://chromewebdata/#buttons)."

в Network - localhost "failed"

### Ожидаемое поведение

Хочу увидеть проект на localhost:3000

### Логи

```shell
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

[Error: EACCES: permission denied, unlink '/home/tsuki1301/Projects/work/drum-in/drum-in/landing/entrypoints/renderer/src/.next/BUILD_ID'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/home/tsuki1301/Projects/work/drum-in/drum-in/landing/entrypoints/renderer/src/.next/BUILD_ID'
}
```

### Медиа-материалы

![3](https://github.com/torin-asakura/drum-in/assets/118632842/d8ef185c-620f-4118-953d-ad507c02010e)
![4](https://github.com/torin-asakura/drum-in/assets/118632842/133d25dd-1be9-4abd-a397-01d413d0abbe)
![5](https://github.com/torin-asakura/drum-in/assets/118632842/a458c122-97cf-4a45-9b51-dd59a8bd3958)
![6](https://github.com/torin-asakura/drum-in/assets/118632842/a6b35b56-b20a-4c70-ae61-03e099279634)

### Действия

Я прочитала руководство по Docker Compose и про monorepo, но как это применить в практике не очень понимаю. 

### Вопрос

Хочу узнать, где я делаю ошибки. Или это как-то связано с настройками ОС Ubuntu?

**Comment by TorinAsakura** [comment]
зачем ты запускаешь команды из-под sudo? sudo - переводится super user DO - то есть исполнение, от имени твоего рут-пользователя, а не от твоего

**Comment by Tsukimono13** [comment]
Без sudo он некоторые команды не запускает и пишет, что у меня нет доступа. Что-то нужно ещё в ubuntu настроить?

**Comment by TorinAsakura** [comment]
> Без sudo он некоторые команды не запускает и пишет, что у меня нет доступа. Что-то нужно ещё в ubuntu настроить?

значит установка производилась не из-под твоего пользователя, переустанавливай и делай это через официальные гайды

**Comment by Tsukimono13** [comment]
![docker-finall](https://github.com/torin-asakura/drum-in/assets/118632842/45973301-d150-4676-89a7-4e5da00c2ca0)

Снесла всё, два раза разными способами переустановила. Изменений нет, проект не окрывает.

**Comment by TorinAsakura** [comment]
> ![docker-finall](https://github.com/torin-asakura/drum-in/assets/118632842/45973301-d150-4676-89a7-4e5da00c2ca0)
> 
> 
> 
> Снесла всё, два раза разными способами переустановила. Изменений нет, проект не окрывает.

Что значит проект не открывает? Последовательность распиши. Ну, или что ты хочешь чтобы я сделал?
