### ISSUE TITLE
Программа для мобильных экранов

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/drum-in#114]
### Описание бага

В странице "Ключи полиритмии" [по дизайну](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1122%3A7706&mode=dev) программа частично на фоне градиента, частично в черном фоне. Однако в WP у нас [программа для всех едина и с черным фоном](https://wp.drumin.pro/wp-admin/upload.php?item=470) и получается такой результат:

<details>

<img width="1431" alt="image" src="https://github.com/torin-asakura/drum-in/assets/44067768/f7d17b3c-da99-4a58-b245-186dc61046c7">

</details>

Пробовал сам экспортировать из фигмы программу с прозрачным фоном - выходит уже частично заполненной:

<details>

![Progress line](https://github.com/torin-asakura/drum-in/assets/44067768/bad5d760-5e28-44ae-b25c-4638055520c3)

</details>

Сможешь дать незаполненную программу с прозрачным фоном? Или даже сам загрузить в WP?

### Воспроизведение

1. https://drumin.pro/polyrhythmic-keys
2. Включить мобильный вид

### Ожидаемое поведение

Программа соответствует дизайну - с прозрачным фоном.

### Материалы

Предоставлены выше.

### Данные окружения

- macOS 13.4.1
- Safari 16.5.2

**Comment by vodopmi** [comment]
@Nelfimov done, загрузил в медиатеку

https://wp.drumin.pro/wp-admin/upload.php?item=965
