### ISSUE TITLE
Блок "Программа" в мобильном виде на всех страницах

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/drum-in#115]
### С чем связан запрос на фичу?

"Программа" в мобильном виде у страницы "Ключи полиритмии" сложно реализуема.

### Расскажите как вы это себе видите

Во всех страницах в мобильном виде "Программа" всегда на черном фоне, что дает нам возможность сделать заполнение прогресса при скролле.

Однако на странице "Ключи полиритмии" программа верхней частью заходит на фон градиента.

Можно было бы сделать так:
1. Сохранить программу в виде картинки с фоном из дизайна и прозрачной "программой"
2. Реализовать заполнение при скролле

Однако фон градиента на странице динамичный и зависит от размера экрана:

<details>
<summary>Видео</summary>

https://github.com/torin-asakura/drum-in/assets/44067768/85268375-97a2-451a-91e8-c4c719faec7c

</details>

@vodopmi вопросы:
1. Нормальное ли поведение фона или он должен быть статичным?
2. Можем ли мы пересмотреть дизайн чтобы программа была так же как на других страницах - в черном фоне?

### Приложите пример реализаций

https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1904%3A16739&mode=dev

**Comment by vodopmi** [comment]
@Nelfimov а если у нас есть два вектора: один серый, а поверх него белый, который имеет такую же форму, просто становится видимым по мере скролла. такое возможно?

**Comment by Nelfimov** [comment]
Тогда думаю будет так по слоям:
1. Наверху - серая программа
2. Черный блок
3. Внизу - белая программа

При скролле черный блок уходит ниже, "открывая" белую программу. Можно воспользоваться хоть `locomotive scroll`, хоть [`framer-motion`](https://www.framer.com/motion/scroll-animations/).

@kalininatonya дай знать ок ли для тебя или видишь другой способ.

**Comment by kalininatonya** [comment]
> Тогда думаю будет так по слоям:
> 
> 1. Наверху - серая программа
> 2. Черный блок
> 3. Внизу - белая программа
> 
> При скролле черный блок уходит ниже, "открывая" белую программу. Можно воспользоваться хоть `locomotive scroll`, хоть [`framer-motion`](https://www.framer.com/motion/scroll-animations/).
> 
> @kalininatonya дай знать ок ли для тебя или видишь другой способ.

Попробую сегодня такой вариант, тоже так думала.

**Comment by vodopmi** [comment]
@kalininatonya https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?type=design&node-id=3471%3A16235&mode=design&t=7736IXSz8oK1mDn1-1 

вот здесь положил рядом два прогресс-лайна. дай знать, пожалуйста, если ещё что-то будет нужно

**Comment by kalininatonya** [comment]
> > вот здесь положил рядом два прогресс-лайна. дай знать, пожалуйста, если ещё что-то будет нужно
> 
> Попробуй пока локальную реализацию. Если получится - я выложу прогрессы в админку.

Получается черный блок будет как раз на черном фоне, на середине полосы прогресса(как в фигме). Ну примерно так: 
![image](https://github.com/torin-asakura/drum-in/assets/133124190/0e1a388f-5391-4bc9-9805-866fd6855cc4)

@Nelfimov Зальешь тогда прогрессы в админку?

**Comment by Nelfimov** [comment]
Обновил на "Ключи полиритмии". Обрати внимание что в GraphQL запросить надо `backgroundMobile2` :

```graphql
query MyQuery {
  coursePolyrhythmicKeys {
    nodes {
      program {
        backgroundMobile {
          sourceUrl
        }
        backgroundMobile2 {
          sourceUrl
        }
      }
    }
  }
}

```

**Comment by kalininatonya** [comment]
Я сделала для мобильной версии, но там пока ужасно для остальных брейкпоинтов(кроме декстопа, там все ок).

**Comment by Nelfimov** [comment]
> Я сделала для мобильной версии, но пока ужасно выглядит для остальных брейкпоинтов(кроме декстопа, там все ок).

Я так понимаю проблема с градиентным бэкграундом. Попробуй зафиксировать его в мобильном виде.

**Comment by kalininatonya** [comment]
> > Я сделала для мобильной версии, но пока ужасно выглядит для остальных брейкпоинтов(кроме декстопа, там все ок).
> 
> Я так понимаю проблема с градиентным бэкграундом. Попробуй зафиксировать его в мобильном виде.

Да, там при ресайзе видно черный квадрат на светлом фоне. Попробую сделать как ты сказал. Для мобилок не посмотрел? Норм?

**Comment by Nelfimov** [comment]
Для мобил - огонь!

**Comment by AlinaLaniuk** [comment]
@Nelfimov мне работать в ветке fix/progressive-bar? или создавать новую от мастера?

**Comment by Nelfimov** [comment]
> @Nelfimov мне работать в ветке fix/progressive-bar? или создавать новую от мастера?

Да

**Comment by Nelfimov** [comment]
> **Какие задачи будешь делать сегодня? Укажи #issues**
> 
> * [Блок "Программа" в мобильном виде на всех страницах torin-asakura/drum-in#115](https://github.com/torin-asakura/drum-in/issues/115) Надо посмотреть сторонние либы, чтобы решить проблему

@AlinaLaniuk почему считаешь что нужны сторонние библиотеки?

**Comment by AlinaLaniuk** [comment]
> > **Какие задачи будешь делать сегодня? Укажи #issues**
> > 
> > * [Блок "Программа" в мобильном виде на всех страницах torin-asakura/drum-in#115](https://github.com/torin-asakura/drum-in/issues/115) Надо посмотреть сторонние либы, чтобы решить проблему
> 
> @AlinaLaniuk почему считаешь что нужны сторонние библиотеки?

я тут имею в виду библиотеки, которые уже затянуты. Конкретно - framer-motion. Ничего нового я не буду добавлять

**Comment by absolemDev** [comment]
@Nelfimov, а мы можем svg использовать? Могу в CodePen пример реализации закинуть для наглядности.

**Comment by Nelfimov** [comment]
Можем. Реализацию можешь сразу в пр показать.

**Comment by absolemDev** [comment]
@Nelfimov, `locomotive-scroll` отменяет нативное событие `scroll`? Я не могу своего слушателя повесить?

**Comment by Nelfimov** [comment]
Попробуй. Форк библиотеки в проекте.

**Comment by absolemDev** [comment]
В процессе поиска оптимизированного решения, сталкивался с различными проблемами. Решил разбить прогресс-бар на компоненты и раскидать логику по ним.
