### ISSUE TITLE
Настройки для `opengraph`

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/drum-in#117]
## С чем связан запрос на фичу

https://drumin.pro не предоставляет мета тегов.

## Что необходимо сделать

Проверить и добавить мета теги. Помимо примера ниже есть реализация в `index-page`, однако надо ее проверять.

<details>
<summary>Запрос на все сущности страниц</summary>

```graphql
query MyQuery {
  pages {
    edges {
      node {
        link
        uri
        title
      }
    }
  }
}

```

</details>

<details>
<summary>Ответ</summary>

```graphql
{
  "data": {
    "pages": {
      "edges": [
        {
          "node": {
            "link": "https://wp.drumin.pro/polyrhythmic-keys/",
            "uri": "/polyrhythmic-keys/",
            "title": "Ключи полиритмии"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/konnakol/",
            "uri": "/konnakol/",
            "title": "Коннакол"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/contacts/",
            "uri": "/contacts/",
            "title": "Контакты"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/seventh-heaven/",
            "uri": "/seventh-heaven/",
            "title": "Седьмое небо"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/fifth-dimension/",
            "uri": "/fifth-dimension/",
            "title": "Пятое измерение"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/a-sense-of-time/",
            "uri": "/a-sense-of-time/",
            "title": "Ощущение времени"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/discovering-the-rhythm/",
            "uri": "/discovering-the-rhythm/",
            "title": "Открытие ритма"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/shkola-ritma-mariny-chuprikovoj/",
            "uri": "/shkola-ritma-mariny-chuprikovoj/",
            "title": "Школа ритма Марины Чуприковой"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/sample-page/",
            "uri": "/sample-page/",
            "title": "Пример страницы"
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

</details>

При удачном ПР мастер ветка улетает в деплой. Через какое то время будет доступна по https://drumin.pro

## Материалы

Проверка: https://www.opengraph.xyz/url/https%3A%2F%2Fdrumin.pro

Либо любой другой сайт для проверки мета тегов

## Примеры реализации

https://github.com/torin-asakura/misik/blob/master/landing/pages/index-page/src/seo.component.tsx

**Comment by absolemDev** [comment]
@Nelfimov, `index-page` отсутствует компонент Seo.

**Comment by absolemDev** [comment]
Импортировал и добавил компонент перед `main`:
```
import {Seo} from "./seo.component";
...
<SpyScroll playSong={playSong} setPlaySong={setPlaySong} />
<Seo language="RU" ogCover={ogCover} SEO={SEO} />
<main style={{ width: '100%', height: '100%' }} data-scroll-container ref={containerRef}>
```
Также удалил ytbcgjkmpetvsq пропс `children`:
```
Seo = ({ language, ogCover, SEO, children }) => {
...
Seo = ({ language, ogCover, SEO }) => {
````
После данных манипуляция локально мета-теги тянутся.

**Comment by TorinAsakura** [comment]
> Импортировал и добавил компонент перед `main`:
> 
> ```
> import {Seo} from "./seo.component";
> ...
> <SpyScroll playSong={playSong} setPlaySong={setPlaySong} />
> <Seo language="RU" ogCover={ogCover} SEO={SEO} />
> <main style={{ width: '100%', height: '100%' }} data-scroll-container ref={containerRef}>
> ```
> 
> Также удалил неиспользуемый пропс `children`:
> 
> ```
> Seo = ({ language, ogCover, SEO, children }) => {
> ...
> Seo = ({ language, ogCover, SEO }) => {
> ```
> 
> После данных манипуляция локально мета-теги тянутся.

зачем ты об этом тут пишешь? 
- Делаешь ветку
- коммитишься в неё
- пушишься
- открываешь ПР
- привязываешь к таске
- запрашиваешь ревью

**Comment by absolemDev** [comment]
@TorinAsakura, не могу запушить ветку, нет доступа.

**Comment by TorinAsakura** [comment]
> @TorinAsakura, не могу запушить ветку, нет доступа.

чтож, доступ я тебе выдал, а где же ветка?

**Comment by absolemDev** [comment]
> чтож, доступ я тебе выдал, а где же ветка?

в ПР
