### ISSUE TITLE
Вынести ID терминала в переменные окружения

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/drum-in#125]
### С чем связан запрос на фичу?

Необходимо хранить ID Тинькофф терминала (касса) в переменных окружения кубера

### Расскажите как вы это себе видите

- [ ] переменная вынесена в окружения
- [ ] переменная имеет префикс `NEXT_PUBLIC_`

**Comment by Nelfimov** [comment]
@absolemDev тегаю чтобы ты мог отслеживать таску и увидеть название переменной.

**Comment by eantdz** [comment]
Если переменная заранее известна мы можем её передавать в deployment (объект k8s) посредством configmap, secret, env, yandex lockbox (remoteRef) если кластер на YC и т.д.

**Comment by Nelfimov** [comment]
От тебя нужно только создать эту переменную и сообщить ее название нам.

Пока можешь занести тестовый ID - 1698844342541DEMO

Реальный ID перешлём как будет готов.

**Comment by eantdz** [comment]
> От тебя нужно только создать эту переменную и сообщить ее название нам.
> 
> 
> 
> Пока можешь занести тестовый ID - 1698844342541DEMO
> 
> 
> 
> Реальный ID перешлём как будет готов.

Эта переменная должна быть скрыта из манифеста в явном виде (секрет) или можно оставить открытой? 

NEXT_PUBLIC_TERMINAL_ID название устроит?

**Comment by Nelfimov** [comment]
`NEXT_PUBLIC_TINKOFF_TERMINAL_ID` будет лучше.

Вроде как `lockbox` подойдет.

**Comment by eantdz** [comment]
https://github.com/atls/infrastructure/pull/95

**Comment by eantdz** [comment]
Выполнено.
