### ISSUE TITLE
Добавление Next ISR для страниц

### ISSUE THREAD

**Issue by oksssvv** [torin-asakura/drum-in#161]
### С чем связан запрос на фичу?

Добавить Incremental Static Regeneration

### Расскажите как вы это себе видите

внедрить [ISR](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration) для страниц:
- [ ] main
- [ ] opening-rhythm
- [ ] feeling-time
- [ ] fifth-dimension
- [ ] seventh-heaven
- [ ] connacol
- [ ] polyrhythmic-keys
- [ ] contacts
- [ ] privacy-policy
- [ ] contract-offer

**Comment by oksssvv** [comment]
@Nelfimov 

не удается реализовать регенерацию контента в main-page

действия:
- getServerSideProps > getStaticProps
- добавление revalidate: 5
- изменение данных в WP 
- в заголовке документа `Cache-Control: no-store, must-revalidate`
- данные не обновляются

при этом очевидно что сайт ждет как раз этой реавалидации, и данные в WP изменены но лайв обновления контента не происходит

что пыталась сделать:
- сбросить кэш apollo graphql
- действовала данному гайду https://purpleschool.ru/blog/nextjs-no-revalidate
- попыталась принудительно вызвать revalidate (успешность не известна, не смогла до конца разобраться удалось ли это сделать)

вопрос:
как еще можно локализовать проблему, куда копать?
что я могла упустить, какие еще возможные причины такого поведения?

- ветка актуальная [feat/incremental-static-regeneration](https://github.com/torin-asakura/drum-in/tree/feat/incremental-static-regeneration)

**Comment by oksssvv** [comment]
@Nelfimov 

так, возможно я ошибалась по поводу не работоспособности ревалидатора, так что уточню:
- используя статические страницы + ISR мы получаем возможность обновления контента на странице, но не совсем в режиме реального времени
на сколько я поняла, при сборке мы получаем статические страницы, запускаем сервер, получаем статичный контент, подключая к страницам ISR мы получаем возможность наблюдать обновленные данные по установленному счетчику, но находясь на странице с уже устаревшим контентом получить новый мы не сможем

пример:
- приходят определенные данные с БД, страница генерируется 
- на сайт заходит пользователь 1 и сидит на главной странице
- в БД меняются данные, например название заголовка на Главной
- заходит пользователь 2, и видит обновленный контент, новый заголовок
- но пользователь 1 все еще видит старый заголовок, пока его страница не будет обновлена 

все так?

**Comment by oksssvv** [comment]
@Nelfimov 

>Пример через /api/webhook - https://github.com/leerob/on-demand-isr/tree/main/app

в 12.3.4 версии некста нет 'next/cache' откуда необходимо забрать revalidatePath, который использовался автором по ссылке которую ты скинул

---

по твоему сценарию все сработало, действия

- сделала в страницах папку api , добавила файл revalidate.ts

```typescript

export default async function handler(req, res) {
  if (parseInt(req.query.secret) !== 987654321) {
    return res.status(401).json({ message: 'Invalid token' })
  }

  try {
    await res.revalidate('/')
    return res.json({ revalidated: true })
  } catch (err) {
    return res.status(500).send('Error revalidating')
  }
}
```

- очистила предыдущий билд, сбилдила заново, запустила start
- перешла а WP изменила данные на главной
- зашла на главную обновила неск. раз > данные старые
- открыла доп страницей `http://localhost:3000/api/revalidate?secret=987654321` > получила `{"revalidated":true}`
- снова обновила главную > данные новые

вопрос:
как дальше действовать?

**Comment by Nelfimov** [comment]
Секрет вынеси в ENV, добавим в проде.

Мержим в мастер.

Сейчас сохрани данные по запросу сайта без кэша чтобы сравнить "стоило ли оно того". Вот мои данные:

<details>

<img width="1335" alt="image" src="https://github.com/torin-asakura/drum-in/assets/44067768/cc52cfc4-4d58-43e9-a98b-4e44c18f2378">

</details>

**Comment by oksssvv** [comment]
@Nelfimov 

несовсем догнала на что именно обратить внимание, надеюсь правильно поняла что на тайминг

в WP изменила данные для Главной, вернула первый бенефит `Научитесь контролировать темп`

- 1 скрин обновила без кеша до принудительной ревалидации 

<details>

![Снимок экрана от 2024-04-11 16-30-17](https://github.com/torin-asakura/drum-in/assets/126156026/835465ba-26f9-42a2-ae7e-5d79eb12762a)
</details>

- 2 скрин обновила без кеша после принудительной ревалидации

<details>

![Снимок экрана от 2024-04-11 16-30-34](https://github.com/torin-asakura/drum-in/assets/126156026/30efc9d4-6b5e-493f-8ccd-2692644bbfe5)

</details>

--- 
что касается секрета и принудительной ревалидации:
- в файле для ревалидации указан путь только к главной странице, для остальных как? секрет вынесу
- также getStaticProps есть только у главной, мне переписать все страницы на него и какой таймаут добавить?
или же пока в качестве теста работаем только с главной?

**Comment by Nelfimov** [comment]
> несовсем догнала на что именно обратить внимание, надеюсь правильно поняла что на тайминг

Все просто - у нас сейчас в проде запущена старая версия без ISR. Для нее я сделал снэпшот с основными метриками. Тебе предлагаю сделать то же самое сейчас _с продом_ и выложить сюда.

Затем, когда выкатим ISR в прод, сделаем повторный замер и посмотрим как изменилось.

> что касается секрета и принудительной ревалидации:
> 
> * в файле для ревалидации указан путь только к главной странице, для остальных как? секрет вынесу

Все страницы надо ревалидировать.

> * также getStaticProps есть только у главной, мне переписать все страницы на него и какой таймаут добавить?

Все страницы. Начнем с одного часа.

>   или же пока в качестве теста работаем только с главной?

Все страницы.

**Comment by oksssvv** [comment]
@Nelfimov 

>Тебе предлагаю сделать то же самое сейчас с продом и выложить сюда.

- обычное обновление Главной на проде `Load: 2.96 s`
<details>

![image](https://github.com/torin-asakura/drum-in/assets/126156026/d2396a10-7508-4dfe-865b-151ae19a1e86)

</details>

- обновление Главной на проде без кэша `Load: 3.26s`
<details>

![image](https://github.com/torin-asakura/drum-in/assets/126156026/1467037c-fb17-42fb-bd58-e913f99a7c49)

</details>

**Comment by Nelfimov** [comment]
Пофикси так же пожалуйста навбар - он должен полностью исчезать при скролле вниз. Сейчас пропадает только фон.

**Comment by Nelfimov** [comment]
А вот результат

<img width="1335" alt="Screenshot 2024-04-12 at 09 18 39" src="https://github.com/torin-asakura/drum-in/assets/44067768/82f9e6fb-781f-4b73-bca9-b73501542665">

2,67 секунды против 4,37
