### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/drum-in#172]
### С чем связан запрос на фичу?

Необходимо проверить SEO и дополнить где необходимо.

### Расскажите как вы это себе видите

- [ ] как минимум подтверждено что нет превью 
- [ ] проверить остальные аттрибуты

**Comment by Nelfimov** [comment]
@oksssvv у меня превью картинка страниц не выводится. Проверь пожалуйста.

Не используемые страницы можешь сносить, предварительно перенеся их данные.

**Comment by oksssvv** [comment]
@Nelfimov 
изображения сконвертировала в `.webp` и добавила в медиафайлы, объем стал меньше. 
Добавила заново на страницы, проверь пожалуйста

**Comment by Nelfimov** [comment]
@oksssvv а превью как тестировала? У меня пока без изменений

**Comment by oksssvv** [comment]
@Nelfimov 

>а превью как тестировала? У меня пока без изменений

смотрю в превью страницы, вот пример `home`:
![image](https://github.com/torin-asakura/drum-in/assets/126156026/5df2ada1-f5fa-4c9f-88c2-f5ab82c9c5b3)

возможно я не верно поняла как это проверить

**Comment by TorinAsakura** [comment]
> @Nelfimov 
> 
> 
> 
> >а превью как тестировала? У меня пока без изменений
> 
> 
> 
> смотрю в превью страницы, вот пример `home`:
> 
> ![image](https://github.com/torin-asakura/drum-in/assets/126156026/5df2ada1-f5fa-4c9f-88c2-f5ab82c9c5b3)
> 
> 
> 
> возможно я не верно поняла как это проверить
> 
> 

https://t.me/WebpageBot

**Comment by oksssvv** [comment]
@Nelfimov 
> перешли себе в какой либо мессенджер ссылку на сайт - должна быть превью.

есть подозрения что это можно сделать при премиуме, других методов добавления особо не вижу, можешь пожалуйста посмотреть?

нашла только что есть возможность добавить изображения для twitter & facebook

**Comment by Nelfimov** [comment]
Посмотри наш https://dream-team.tech/

Там есть превью
