### ISSUE TITLE
Тинькофф касса: необходимо получать ID по GraphQL

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/drum-in#176]
### С чем связан запрос на фичу?

Необходимо получать ID Тинькофф кассы через GraphQL

### Расскажите как вы это себе видите

- [x] ID Тинькофф кассы получаем через GraphQL
- [x] из кода убираем все следы ID

**Comment by oksssvv** [comment]
@Nelfimov 

правильно ли понимаю, что необходимо:
создать новую запись, затем группу полей для общих фрагментов, например `Оплата`, туда закинуть данные для полей (плейсхолдеры для имени, почты, телефона и текста в кнопке) и дополнительно добавить `storeId` содержащий id для виджета

и далее получать в коде для всех пэйментов через ssg + isr от страниц

**Comment by Nelfimov** [comment]
Нужно только ID кассы добавить в WP и вытягивать через graphql. Можешь создать для этого новый тип записи типа "Настройки сайта"/"Настройки оплаты" и там держать.
