### ISSUE TITLE
баги в стрейдже

### ISSUE THREAD

**Issue by oksssvv** [torin-asakura/drum-in#177]
### Описание бага

необходимо исправить баги стейджа на разных вьюпортах сайта:

- [x] `mobile`/`contacts/footer` получить данные
- [x] `mobile`/`header` отступ сверху элементов в выпадающем
- [x] `mobile & desktop`/`header`констульация при клике по `связаться` 
- [x] `laptop`/`contract-offer` ширина заголовка
- [x] `mobile & desktop`/`main` передавать данные в модал при клике по `записатсья`
- [x] `desktop`/`выберите курс` центрировать текст в квадратных фигурах (macOS)
- [x] `mobile`/`connacol/курс вам поможет` левый отступ в слайдере
- [x] `mobile`/`opening/состав курса` левый отступ в слайдере
- [x] `mobile`/`opening/после курса вы сможете` скрытие текста в бегущей строке (macOS)
- [x] `mobile`/`все мобильные модалки оплаты` сжатие чекбокса из-за длинны текста в лейбле 
- [x] `mobile`/`все консультации и оплата` необходимо закрытие при касании по верхнему элементу шторки

### Ожидаемое поведение

все корректно отображается

### Материалы

[design](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?type=design&node-id=835-2537&mode=design&t=Na3NZ7udrfeQDpTR-0)

**Comment by oksssvv** [comment]
@Nelfimov 

я поисследовала сайт с айфона и при окне оплаты у меня почти нет свободного места что бы кликнуть для закрытия оплаты, я подумала что как раз этот верхний фрагмент (округленная горизонтальная полосочка сверху) должен быть как вспомогательный элемент для закрытия

<details>

![image](https://github.com/torin-asakura/drum-in/assets/126156026/18c92a42-e6c4-4ef9-bedb-81c3f14aee93)

</details>

вопрос:
мне повесить на него закрытие оплаты?

**Comment by Nelfimov** [comment]
> вопрос:
> мне повесить на него закрытие оплаты?

Хорошая находка.

Да. В идеале - она должна закрываться свайпом сверху вниз по шторке.
