### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#33]
### Задача
Сделать фрагмент [Header](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19460)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
При открытии [меню](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1780%3A16722&t=s511EKOn8xHUe1Cc-4) (из-за того, что оно появляется сверху вниз) появляется [такой баг.](https://drive.google.com/file/d/1irxUl-_WRnShNBdA2s1XKNtxjYQ5wiBm/view?usp=sharing) Как его можно исправить?
[Контекст](https://github.com/torin-asakura/drum-in/tree/feat/main-page/ui/drawer/src)

**Comment by TFK70** [comment]
> @TFK70 При открытии [меню](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1780%3A16722&t=s511EKOn8xHUe1Cc-4) (из-за того, что оно появляется сверху вниз) появляется [такой баг.](https://drive.google.com/file/d/1irxUl-_WRnShNBdA2s1XKNtxjYQ5wiBm/view?usp=sharing) Как его можно исправить? [Контекст](https://github.com/torin-asakura/drum-in/tree/feat/main-page/ui/drawer/src)

Если баг - используй [шаблон для бага](https://github.com/atls/serenity/blob/dev/.github/ISSUE_TEMPLATE/bug.md), там есть пункт `Ожидаемое поведение` которого у тебя как раз не хватает. Я вообще не понял в чём тут баг

**Comment by TFK70** [comment]
@eshevlyakova ты пытаешься отрендерить объект, вместо react компонента

Убирай компоненты по одному, пока приложение не заработает. Когда поймешь какой компонент проблемый - делай в нём то же самое, пока не найдешь проблемный элемент

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Блокировка ховер эффекта, пока не закончится анимация

### Описание

При клике на кнопку курсы появляется backdrop, а меню нет

### Контекст

[Коммит](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/drawer/src/drawer.component.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Видим header и нажимаем на кнопку курсы

### Ожидаемое поведение

При клике на кнопку курсы выезжает меню и ховер эффект заблокирован, пока не закончится анимация

### Медиа-материалы

<img width="1280" alt="Снимок экрана 2022-11-30 в 14 06 55" src="https://user-images.githubusercontent.com/79781486/204780516-04c45638-9282-43d3-99fe-cf544979bbfe.png">


### Действия

1. В зависимость к хуку useEffect добавила параметр active, но тогда меню один раз выезжало, и больше не заезжало (разобралась почему)

### Вопрос

1. Как сделать так, чтобы при клике на кнопку курсы меню выезжало и в переменной stateAnimation было true?

**Comment by TFK70** [comment]
> В зависимость к хуку useEffect добавила параметр active, но тогда меню один раз выезжало, и больше не заезжало (разобралась почему)

Вообще-то это правильное решение было, я не понял в чем проблема в итоге

**Comment by TFK70** [comment]
> @TFK70 Если [сюда](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/drawer/src/drawer.component.tsx#L22) пишу active, то меню работает так: https://drive.google.com/file/d/1hU68nWDa678ZP84XqlmiJfu8qqfB8JEa/view?usp=sharing

У меня все норм
Сделал коммит, проверь

**Comment by eshevlyakova** [comment]
@TFK70 да теперь все работает, я просто забыла убрать лишние пропсы у motion. 
А как передать переменную stateAnimation к [{children}](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/drawer/src/drawer.component.tsx#L41)?

**Comment by TFK70** [comment]
> @TFK70 да теперь все работает, я просто забыла убрать лишние пропсы у motion. А как передать переменную stateAnimation к [{children}](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/drawer/src/drawer.component.tsx#L41)?

не знаю

**Comment by eshevlyakova** [comment]
@TFK70 
> не знаю

То есть у меня неправильная структура или вообще не должно быть {children}? Я просто гуглила и ничего не нашла

**Comment by TFK70** [comment]
@eshevlyakova Это работа с js чистая
Это я скорее к тому что у тебя реквест составлен неверно. Точнее это вообще на реквест не похоже

**Comment by TFK70** [comment]
@eshevlyakova ты можешь сделать children коллбеком:

```jsx
const Drawer = ({ children }) => {
   const someValue = {}
   return (
      <Box>
         {typeof children === 'function' ? children(someValue) : children}
      </Box>
   )
}
```

И использовать это так:

```jsx
```

**Comment by eshevlyakova** [comment]
@TFK70 
Меню сейчас закрывается вот так: https://drive.google.com/file/d/1yD2gp3O7yOO_FOC1qvwwtuXdsUA2sDhS/view?usp=sharing
Раньше оно также заезжало наверх, это из-за того, что [тут](https://github.com/torin-asakura/drum-in/commit/f2849694cf3f353366445bfb9829287e96c8122c#diff-2913aa1d1b65ffe69cdbe705283a3077aca0ab82481b9e934130e80d5e4ac382L40) убрали этот пропс. Оставлять так?

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Анимация закрытия меню

### Описание

Меню при закрытии просто исчезает, вместо плавного поднятия вверх

### Контекст

[Коммит](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/drawer/src/drawer.component.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Открываем меню
3. Закрываем меню

### Ожидаемое поведение

При закрытии меню, оно плавно поднимается вверх

### Действия

1. После [этой строчки](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/drawer/src/drawer.component.tsx#L38) я добавила пропс: `exit={{ top: '-100%' }}`, но тогда меню не закрывалось в принцепе

### Вопрос

1. Как сделать плавное закрытие меню или пропустить?

**Comment by TFK70** [comment]
@eshevlyakova потому что у тебя на каждое изменение `active` на [этой](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/drawer/src/drawer.component.tsx#L23) строчке срабатывает анимация появления, даже когда active === false

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Менять фон с прозрачного на темный при скролле вверх

### Описание

Делала по примеру сайта [misik](https://github.com/torin-asakura/misik/blob/master/landing/fragments/landing-navigation/src/navigation.component.tsx#L37). Шапка цвет фона меняет, но при это секции отображаются не там где должны. 

### Контекст

[Код шапки](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-header/src/header.component.tsx)
[Код главной страницы](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/pages/index-page/src/index.page.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`

### Ожидаемое поведение

Сайт запускается, все секции отображаются и header меняет цвет фона при разном направлении скролла

### Медиа-материалы

<img width="1280" alt="Снимок экрана 2022-12-26 в 10 20 41" src="https://user-images.githubusercontent.com/79781486/209517343-cdcd588c-b95a-4fac-bbe2-fc5ab5cb69fe.png">

### Вопрос

1. Из-за чего сайт так отображается и как это исправить?

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
