### ISSUE TITLE
Hero - Главная страница

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#34]
### Задача
Сделать фрагмент [Hero](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19265)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
Если [заголовок](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19276&t=8Qy54JWRoydcG3aL-4) отрисован в дизайне мне его, как svg иконку использовать?

**Comment by eshevlyakova** [comment]
@TorinAsakura 
> Или ты рассматриваешь какие-либо альтернативы?

Нет. Просто уточнила, мало ли есть какой-то способ о котором я забыла

**Comment by eshevlyakova** [comment]
@TFK70 как сделать такую же [анимацию иконки](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19275&t=vXPmVXz2FMGQ8DK2-4) при наведении?

**Comment by TFK70** [comment]
@eshevlyakova через css, вариантов море на самом деле, можешь через маржины

В globals через keyframes описываешь анимацию, а в иконке используешь её [таким](https://github.com/torin-asakura/misik/blob/master/ui/copy/src/copy-success.icon.tsx) способом

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Использование хука useHover от react laag

### Описание

Не могу понять синтаксис использования UseHoverProps

### Контекст

https://github.com/everweij/react-laag#usehoverprops

### Действия

1. Гуглила документации и примеры работ, но ничего не нашла

### Вопрос

1. Как использовать onMouseEnter? К примеру для этой строки:
```tsx
const [hover, hoverProps] = useHover();
```

**Comment by TFK70** [comment]
@eshevlyakova сделай `console.log(hoverProps)`, посмотри что там внутри

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
