### ISSUE TITLE
Courses

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#36]
### Задача
Сделать фрагмент [Courses](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19279)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Создание слайдера

### Описание

Не знаю какое значение задать параметру slidesPerView, чтобы количество рассчитывалось автоматически (в зависимости от ширины слайдера). Это нужно для того, чтобы на экранах меньше слайды нормально выглядели. Сейчас я задала slidesPerView='auto' и отображается только по одному слайду.

### Контекст

[Слайдер](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-choose-course/src/slider/slider.component.tsx#L16)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Листаем до блока со слайдером 

### Ожидаемое поведение

Слайдер в зависимости от ширины экрана и слайда рассчитывает количество отображаемых слайдов

### Медиаматериалы
Вот так отображаются слайды по 3 штуки(slidesPerView={3}) на 13 дюймах:
<img width="1280" alt="Снимок экрана 2022-12-05 в 17 41 37" src="https://user-images.githubusercontent.com/79781486/205664637-f85b1f65-b27d-473f-8f85-f3666a1d1280.png">

А так сейчас в принципе отображается слайдер:
<img width="1280" alt="Снимок экрана 2022-12-05 в 17 39 53" src="https://user-images.githubusercontent.com/79781486/205664250-f4ff95d8-cf6a-4ad4-ba6b-52c75858a597.png">

### Действия

1. Погуглила и посмотрела доку, но ничего не нашла

### Вопрос

1. Это возможно реализовать? Если нет, то чем можно заменить мою идею?

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Убираю items и подгружаю данные с shared/data/src/mocks/courses

### Описание

Когда выгружала эти данные для обычных блоков все работало, но со слайдером возникла ошибка

### Контекст

[Данные](https://github.com/torin-asakura/drum-in/tree/feat/main-page/shared/data/src/mocks/courses)
[Слайдер](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-choose-course/src/slider/desktop-slider/desktop-slider.component.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Видим ошибку

### Ожидаемое поведение

Сайт запускается без ошибок

### Логи

```shell
Check the top-level render call using <Condition>. See https://reactjs.org/link/warning-keys for more information.
    at Repeater (webpack-internal:///../../../../.yarn/__virtual__/@ui-utils-virtual-030ab2c95f/1/ui/utils/src/components/repeater/repeater.component.tsx:13:21)
    at div
    at /Users/j_sh/Desktop/drum-in/.yarn/__virtual__/@emotion-react-virtual-8231f7e4e6/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at div
    at /Users/j_sh/Desktop/drum-in/.yarn/__virtual__/@emotion-react-virtual-8231f7e4e6/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at div
    at /Users/j_sh/Desktop/drum-in/.yarn/__virtual__/@emotion-react-virtual-8231f7e4e6/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at TapeBlock (webpack-internal:///../../../../.yarn/__virtual__/@landing-tape-fragment-virtual-deb2aa60b3/1/landing/fragments/landing-tape/src/tape.component.tsx:32:72)
    at div
    at /Users/j_sh/Desktop/drum-in/.yarn/__virtual__/@emotion-react-virtual-8231f7e4e6/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Hero
    at div
    at /Users/j_sh/Desktop/drum-in/.yarn/__virtual__/@emotion-react-virtual-8231f7e4e6/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at HomePage
    at ThemeProvider (/Users/j_sh/Desktop/drum-in/.yarn/__virtual__/@emotion-react-virtual-8231f7e4e6/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:106:21)
    at ThemeProvider (webpack-internal:///../../../../.yarn/__virtual__/@ui-theme-virtual-8835c06af0/1/ui/theme/src/theme.provider.tsx:18:26)
    at IntlProvider (/Users/j_sh/Desktop/drum-in/.yarn/__virtual__/react-intl-virtual-e5b9f65fb2/0/cache/react-intl-npm-5.24.3-c8cb0c2bf3-e6ff97632f.zip/node_modules/react-intl/src/components/provider.js:81:47)
    at App (webpack-internal:///./pages/_app.tsx:19:16)
    at StyleRegistry (/Users/j_sh/Desktop/drum-in/.yarn/__virtual__/styled-jsx-virtual-54dd4d700b/0/cache/styled-jsx-npm-5.0.0-23d0c7994a-4958238ac8.zip/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/j_sh/Desktop/drum-in/.yarn/__virtual__/next-virtual-daf36fb0ce/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/j_sh/Desktop/drum-in/.yarn/__virtual__/next-virtual-daf36fb0ce/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/Users/j_sh/Desktop/drum-in/.yarn/__virtual__/next-virtual-daf36fb0ce/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/server/render.js:715:21)
```

### Действия

1. Искала примеры и сделала, как [тут](https://github.com/atls/kino-reporter/blob/aaca06bf778589dbfabd1027dee0f68abb16fdaf/site/app/fragments/films-and-serials/src/cinema/cinema.component.tsx), но ошибка осталась

### Вопрос

1. Из-за чего эта ошибка и как ее исправить?

**Comment by carminio** [comment]
@eshevlyakova для десктопа коммитнул фикс, для мобилки сделай по подобию, [тут](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/slider/src/slider.component.tsx) пропсы еще доделай, которые нужно будет прокидывать 

[Стреляешь](https://github.com/torin-asakura/drum-in/blob/feat/main-page/shared/data/src/mocks/courses/courses.mock.ts#L9-L27) себе в ногу, ui логика с бека идти не будет, нужно убрать

**Comment by eshevlyakova** [comment]
@carminio
> [Стреляешь](https://github.com/torin-asakura/drum-in/blob/feat/main-page/shared/data/src/mocks/courses/courses.mock.ts#L9-L27) себе в ногу, ui логика с бека идти не будет, нужно убрать

А откуда и как ui подгружать? Если для каждого item свои значения

**Comment by eshevlyakova** [comment]
@carminio
> для десктопа коммитнул фикс

И ты вынес [слайдер ](https://github.com/torin-asakura/drum-in/tree/feat/main-page/ui/slider)в ui, но у меня много слайдеров, с разными атрибутами и значения, их все нужно выносить в ui или только этот один будет?

**Comment by carminio** [comment]
> И ты вынес [слайдер ](https://github.com/torin-asakura/drum-in/tree/feat/main-page/ui/slider)в ui, но у меня много слайдеров, с разными атрибутами и значения, их все нужно выносить в ui или только этот один будет?

то что ты [добавляешь](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-choose-course/package.json#L13) свайпер каждый раз фрагмент, это в корне неверно. Да, будет ток один, который в ui, контролировать можешь через [пропсы](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/slider/src/slider.component.tsx#L5), я же по-этому и написал добавь пропсы, которые нужны будут.
[Это](https://github.com/torin-asakura/drum-in/blob/feat/main-page/ui/slider/src/slider.component.tsx#L8-L12) закинь в пропсы и всё в таком духе что нужно, будет в пропсах

**Comment by carminio** [comment]
@eshevlyakova 
> А откуда и как ui подгружать? Если для каждого item свои значения

В этом и рофл, что ui ниоткуда подгружать не нужно, с бека придут текста и картинки, позиционировать нужно на месте, это уже вопрос реализации

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
