### ISSUE TITLE
Teacher

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#37]
### Задача
Сделать фрагмент [Teacher](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19368)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
При клике на [эту кнопку](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19390&t=GBrkHCjslMVvIN7Y-4) должна включаться музыка?

**Comment by TFK70** [comment]
@eshevlyakova https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94?node-id=1923:19253#324471348

**Comment by eshevlyakova** [comment]
@TFK70 а можешь пожалуйста прислать пример реализации воспроизведения аудио при клике на кнопку?
Я искала примеры, и везде при клике  происходит интеграция с apple music

**Comment by TFK70** [comment]
@eshevlyakova В html есть тег специальный для проигрывания аудио, нам не нужны интеграции со стриминговыми сервисами, музыка будет в виде файла

**Comment by TFK70** [comment]
@eshevlyakova кинул фикс, свг немного битые были с одинаковым pattern id

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
