### ISSUE TITLE
Learning process

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#39]
### Задача
Сделать фрагмент [Learning process](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19428)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
[Эти картинки](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19431&t=hyQT2nKLPmwQxnBm-4) должны прокручиваться (то есть у слайдера автоплей)?

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
