### ISSUE TITLE
Students

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#40]
### Задача
Сделать фрагмент [Students](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19443)

Фулл [фрагмент](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1816%3A15761)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
[Этот список](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1780%3A20107&t=71CE1Tm13YksRbpU-4) должен скролиться по вертикали?

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Верстка тега для учеников

### Описание

Тег сжимается по ширине, хотя в родительском блоке еще есть место. Или переносятся слова текста и сохраняются отступы, или если это одно длинное слово, то оно выходит за пределы блока. 

### Контекст

[Код](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-students/src/modal-window/students-list/one-student/one-student.component.tsx#L41-L62)
[Элемент в фигме](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1780%3A20224&t=THCnxo89ny4eC1Gd-4)

### Воспроизведение

1. Запускаем сайт - `yarn workspace @landing/renderer-entrypoint run dev`
2. Спускаемся до последнего блока и кликаем на кнопку "Смотреть еще"
3. Видим что два тега у каждого ученика сжимаются по ширине

### Ожидаемое поведение

Слова не переносятся и все отступы сохраняются (в общем как в дизайне)

### Медиа-материалы

<img width="664" alt="Снимок экрана 2022-12-15 в 14 28 17" src="https://user-images.githubusercontent.com/79781486/207848029-1a15dfb0-595d-44ad-b9bd-b97edd151746.png">


### Действия

1. Запрещала перенос по словам для элемента Text
2. Указывала flexShrink={0} для самого тега

### Вопрос

1. Почему так происходит и как это исправить?

**Comment by carminio** [comment]
@eshevlyakova в тэгах, бейджах допустимо использовать padding, вообще рекомендую вынести это в ui (ui/tag).
главному [Box](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-students/src/modal-window/students-list/one-student/one-student.component.tsx#L64) задаешь p='4px 12px', остальное убираешь.

Плюс обращай внимание на горизонтальные отступы
<img width="158" alt="image" src="https://user-images.githubusercontent.com/35490768/207854242-ad79c39f-5eb0-4d12-ae30-42ad3de34d00.png">
Флексы сжирают их и в итоге у тебя вместо 20 -> 18. юзай flexShrink={0}

**Comment by eshevlyakova** [comment]
@TFK70 
А что делать с карточками учеников на разрешении 1280px (macbook 13)?
<img width="1280" alt="Снимок экрана 2022-12-16 в 09 52 10" src="https://user-images.githubusercontent.com/79781486/208039911-297428e4-802e-4500-ade3-aae0f94dc810.png">
Может через слайдер с автоматическим расчетом количества показываемых слайдов? То есть на 1920px все будет также (потому что все слайды помещаются), а на экранах меньше будет слайдер

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Использование mocks

### Описание

Не могу понять как подгружать иконки (которые появляются при наведении) с mocks, ведь для каждой карточки в зависимости от профессии будут свои иконки (и по идее с их позиционированием тоже проблема, ведь как я могу передавать значения для top/left если не знаю для какой иконки)

### Контекст

[Код](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-students/src/cards-student/cards-student.component.tsx#L29-L142)
[Макет](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19443&t=jJ4AouZvNVH7VRyk-4)

### Медиа-материалы

<img width="1280" alt="Снимок экрана 2022-12-22 в 13 39 38" src="https://user-images.githubusercontent.com/79781486/209116605-1c3abe44-0d05-4c53-ab2c-3d887f2843ba.png">

### Вопрос

1.  Будут ли на wordpress меняться иконки или же у этих карточек не будет меняться профессия и соответственно картинки с инструментами?
2. Если меняться будут, то как это можно реализовать?

**Comment by carminio** [comment]
@eshevlyakova сделай хелпер - простая функция, которая будет принимать ключ и отдавать результат. Сделай условия по ключу который будет приходит с сервера пусть он будет называться itemId и если itemId === условию значит будут такие-то значения, и в таком случае не нужно ничего никуда передавать, наподобие этого [беспредела](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-students/src/cards-student/cards-student.component.tsx#L81). Далее этот хелпер юзай в самом [Item](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-students/src/cards-student/item/item.component.tsx)

**Comment by eshevlyakova** [comment]
@carminio то есть иконки меняться не будут и если там к примеру профессия такая-та, то я вставляю такие-то иконки?

**Comment by carminio** [comment]
> @carminio то есть иконки меняться не будут и если там к примеру профессия такая-та, то я вставляю такие-то иконки?

Верно
Также ItemId который будет приходить с сервера это просто ключ: значение
itemId: 'guitarCard'
Отсюда если ItemId (у которого значение guitarCard) === 'guitarCard' значит возвращаешь объект в котором у тебя будет и позиционирование, и все что там ещё нужно.
Иконки рекомендую просто в самом компоненте Item сразу же вставить просто обернуть каждую в Condition match=itemId === '...'

**Comment by eshevlyakova** [comment]
>> @carminio то есть иконки меняться не будут и если там к примеру профессия такая-та, то я вставляю такие-то иконки?

> Верно

А в [меню](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1780%3A16994&t=I4Vgl0ImDm3SHUlj-4) и в [слайдере курсов](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19282&t=I4Vgl0ImDm3SHUlj-4) такой же принцип? Потому что там в каждом элемемнте меняется цвет, положение и последовательность фигур

**Comment by carminio** [comment]
> > > @carminio то есть иконки меняться не будут и если там к примеру профессия такая-та, то я вставляю такие-то иконки?
> 
> > Верно
> 
> А в [меню](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1780%3A16994&t=I4Vgl0ImDm3SHUlj-4) и в [слайдере курсов](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19282&t=I4Vgl0ImDm3SHUlj-4) такой же принцип? Потому что там в каждом элемемнте меняется цвет, положение и последовательность фигур

++

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
