### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#41]
### Задача
Сделать фрагмент [FAQ](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19444)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Анимация вопросов при наведении

### Описание

Не понимаю как при наведении на иконку перевернутого восклицательного знака (когда появляется блок с ответом), менять фон всех остальных блоков с вопросами

### Контекст

[Код](https://github.com/torin-asakura/drum-in/tree/feat/main-page/landing/fragments/landing-faq/src/list-desktop)
[Блок в фигме](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19444&t=NxnGwoWJIcSci32V-4)

### Ожидаемое поведение

Должна получиться анимация как в фигме в режиме презентации

### Медиа-материалы

При наведении на один элемент все остальные должны стать такими:
<img width="1280" alt="Снимок экрана 2022-12-16 в 16 27 56" src="https://user-images.githubusercontent.com/79781486/208108630-43c46733-d15a-40b6-be57-535972f87986.png">

### Действия

1. Думала создать в [списке с вопросами](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/list-desktop.component.tsx) переменную с состоянием и изменять ее в item при наведении на перевернутый восклицательный знак. И также передавать эту же самую переменную в качества параметра для всех вопросов и с помощью нее менять фон (`backgroundColor={state ? black : white}`)

### Вопрос

1. Не понимаю как реализовать свою идею. Для начала как изменять родительскую переменную в ребенке?

**Comment by carminio** [comment]
@eshevlyakova 

I. [Такие](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/list-desktop.component.tsx) списки с айтемами, руками не делаем, отрисосываем через `map` [пример](https://github.com/atls/kino-reporter/blob/master/site/app/fragments/interviews/src/interviews.component.tsx#L71). 
Почему не руками? 
Во-первых, эти данные будут идти с бека в виде массива (можешь конечно вытягивать каждый элемент поштучно, но это же бред + неудобно)
Во-вторых, ну не будешь же 1000 элементов копипастой отрисовывать как это сделано сейчас, значит как минимум меньше кода + удобно.
P.S нужно будет переделать везде, где руками так айтемы копипастала, онли через map

II. Заинить https://github.com/atls/kino-reporter/blob/master/ui/utils/src/hooks/use-popover.hook.ts

III. [Здесь](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/item/item.component.tsx) объявляешь сам хук ([пример](https://github.com/atls/kino-reporter/blob/master/site/app/fragments/header/src/header.component.tsx)):
```tsx
  const { triggerProps, layerProps, render, isOpen } = usePopover('bottom-right', 9, 'hover')
```

IV. [Здесь](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/list-desktop.component.tsx) делаешь стейт, после прокидываешь active и setActive в Item
```tsx
  const [active, setActive] = useState<boolean>(false)
```
V. В компоненте Item:
```tsx
 const getColor = (isOpen, active) => {
    if (isOpen) return 'background.smokyWhite'
    if (!isOpen && active) return 'background.purple'

    return 'background.smokyWhite'
  }

  return (
    <Box
      width={width}
      position='relative'
      borderRadius='extra'
      backgroundColor={getColor(isOpen, active)}
    >
```

getColor вынеси в landing-faq/src/helpers

**Comment by carminio** [comment]
@eshevlyakova 

I. [Такие](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/list-desktop.component.tsx) списки с айтемами, руками не делаем, отрисовываем через `map` [пример](https://github.com/atls/kino-reporter/blob/master/site/app/fragments/interviews/src/interviews.component.tsx#L71). 
Почему не руками? 
Во-первых, эти данные будут идти с бека в виде массива (можешь конечно вытягивать каждый элемент поштучно, но это же бред + неудобно)
Во-вторых, ну не будешь же 1000 элементов копипастой отрисовывать как это сделано сейчас, значит как минимум меньше кода + удобно.
P.S нужно будет переделать везде, где руками так айтемы копипастала, онли через map

II. Заинить https://github.com/atls/kino-reporter/blob/master/ui/utils/src/hooks/use-popover.hook.ts

III. [Здесь](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/item/item.component.tsx) объявляешь сам хук ([пример](https://github.com/atls/kino-reporter/blob/master/site/app/fragments/header/src/header.component.tsx)):
```tsx
  const { triggerProps, layerProps, render, isOpen } = usePopover('bottom-right', 9, 'hover')
```

IV. [Здесь](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/list-desktop.component.tsx) делаешь стейт, после прокидываешь active и setActive в Item
```tsx
  const [active, setActive] = useState<boolean>(false)
```
V. В компоненте Item:
```tsx
 const getColor = (isOpen, active) => {
    if (isOpen) return 'background.smokyWhite'
    if (!isOpen && active) return 'background.purple'

    return 'background.smokyWhite'
  }

  return (
    <Box
      width={width}
      position='relative'
      borderRadius='extra'
      backgroundColor={getColor(isOpen, active)}
    >
```

getColor вынеси в landing-faq/src/helpers

**Comment by eshevlyakova** [comment]
@carminio
> [Такие](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/list-desktop.component.tsx) списки с айтемами, руками не делаем, отрисовываем через map [пример](https://github.com/atls/kino-reporter/blob/master/site/app/fragments/interviews/src/interviews.component.tsx#L71).

А как и где мне тогда хранить текста? Сейчас они в landing/entrypoints/renderer/locales/ru.json и в виде строки. Я так поняла у меня должен быть массив с объектами и мне его также хранить в ru.json в таком виде:
```json
"faq": "{ question: 'Вопрос 1', answer: 'Ответ 1' }; { question: 'Вопрос 2', answer: 'Ответ 2'}"
```
А в самом файле компонента разбить методом split на массив, так?

**Comment by carminio** [comment]
@eshevlyakova учитывая что это все будет тянуться с вордпресса, насколько мне известно, здесь в принципе этот файл будет не нужен, [Пример](https://github.com/torin-asakura/misik/blob/master/landing/fragments/landing-reviews/src/item/item.component.tsx#L67)

Делай пока по подобию https://github.com/atls/kino-reporter/tree/master/shared/data/src

**Comment by eshevlyakova** [comment]
@carminio 
Можно для [item вопроса](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19444&t=GyQSH9SBJlAbwapB-4) использовать горизонтальные падинги? 
Потому что flexBasis + flexShrink не работает (похожая ситуация была [тут](https://github.com/torin-asakura/drum-in/issues/40#issuecomment-1352930620)), а если явно указывать ширину, то если поменять текст, все сломается
[Код](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/item/item.component.tsx#L27)

**Comment by TFK70** [comment]
@eshevlyakova да, в таких местах это допустмо

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
