### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#43]
### Задача
Сделать фрагмент [Footer](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1923%3A19459)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Кнопка вверх

### Описание

Не могу найти рабочие способы для реализации прокрутки вверх при клике на кнопку

### Контекст

[Кнопка](https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-footer/src/content-footer/button-up/button-up.component.tsx)

### Ожидаемое поведение

При клике на кнопку страница плавно прокручивается в самый вверх

### Действия

1. Искала примеры в существующих работах
2. Пробывала сделать с помощью window.scrollTo
3. Гуглила

### Вопрос

1. Как сделать прокрутку вверх?

**Comment by TFK70** [comment]
@eshevlyakova locomotive scroll переопределяет поведение скролла на твоем сайте, поэтому window.scrollTo бесполезен
Для этого используй апи самого locomotive scroll - https://github.com/locomotivemtl/locomotive-scroll#with-methods

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
