### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#45]
### Задача
Сделать фрагмент [Sounds](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1799%3A14614)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Показывать кнопку, только вне определенной секции

### Описание

Взяла за пример [ui с проекта misik](https://github.com/torin-asakura/misik/tree/master/ui/spy-scroll). Для начала не могу понять, откуда в моем случае будут браться названия секций. В примере [они берутся с apollo].(https://github.com/torin-asakura/misik/blob/master/ui/spy-scroll/src/data/useSteps.ts#L6)
Моя задумка в том, что я сделаю проверку: если id текущей секции не равно teacher, то буду показывать кнопку, иначе скрывать

### Контекст

[Элемент и его описание в фигме](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1799%3A14614&t=scomsHFC19UOB28A-4)

### Ожидаемое поведение

Кнопка будет появляться, когда мы вне секции "учитель"


### Вопрос

1. Как реализовать свою идею? Где прописывать id секциям и как их правильно доставать для ui/spy-scroll

**Comment by carminio** [comment]
@eshevlyakova а кнопки самой нет сейчас? или куда смотреть
Тебе нужен будет хук [useIntersectionObserver](https://github.com/torin-asakura/misik/blob/master/landing/pages/index-page/src/index.page.tsx#L37), в компоненты [прокидываешь](https://github.com/torin-asakura/misik/blob/master/landing/pages/index-page/src/index.page.tsx#L49-L54) пропсы. В самих компонентах указываешь [ref](https://github.com/torin-asakura/misik/blob/master/landing/fragments/landing-hero/src/hero.component.tsx#L41)

Там где в ui/spy-scroll фетчатся id шагов, можешь моки сделать

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/53
