### ISSUE TITLE
Hero - Страница "Открытие ритма"

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#46]
### Задача
Сделать фрагмент [Hero](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1442%3A16530)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Создание подобных страниц курсов

### Описание

Я так понимаю что мне не нужно для одинаковых блоков (где отличается только текст и цвет) создавать отдельные компоненты в fragments. Я должна подгружать текст и id из mocks. Но не могу понять как, то есть это же не слайдер, мне не нужно вставлять все объекты из mocks, а только один. 

### Вопрос

1. Я правильно понимаю, что мне нужно передавать id страницы в mocks и в landing/pages/ в файле каждой страницы делать цикл (как везде) с условием если итерируемого id равно текущему id, и когда он совпадает передавать текст? 
Пример: 
```tsx
 {pagesHero.map(({ id }) => {
   if (id === 'feeling-of-time-page') {
     return ...
   }
})}
```

**Comment by carminio** [comment]
@eshevlyakova можешь сделать ещё проще, проверять по роуту прям в самом компоненте на какой странице находишься и уже за счёт этого отрисовывать необходимые текста

проверять на каком роуте находишься можно через [useRouter](https://github.com/atls/kino-reporter/blob/feat/tabs/site/app/fragments/header/src/header.component.tsx#L39) 
`router.route`

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/54
