### ISSUE TITLE
After the course

### ISSUE THREAD

**Issue by carminio** [torin-asakura/drum-in#47]
### Задача
Сделать фрагмент [After the course](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1442%3A16537)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Адаптация блока под экраны 1280px

### Описание

[По совету дизайнера](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94?node-id=1442:16516#337572002) я хочу убрать стрелку и пододвинуть чуть-чуть вправо блок с бегущими строками, но брекпоинты по умолчанию этого не позволяют

### Контекст

[Секция](https://github.com/torin-asakura/drum-in/blob/feat/opening-the-rhythm-page/landing/fragments/landing-after-the-course/src/landing-after-the-course.component.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Переходим на страницу "Открытие ритма" (через выдвигающееся меню)
3. Скролим до секции "После курса" 

### Ожидаемое поведение

На небольших ноутбуках секция отображается корректно (ни один из элементов не заходит за границу)

### Медиа-материалы

<img width="1278" alt="Снимок экрана 2023-01-04 в 13 15 49" src="https://user-images.githubusercontent.com/79781486/210533270-c1001453-ff74-42a9-bc48-34c60ba19ebb.png">

### Вопрос

1. Как добавить брекпоинт для этого разрешения и только для этого блока/элемента?

**Comment by TFK70** [comment]
@eshevlyakova можешь добавить в theme кастомный брейкпоинт и использовать его в компоненте - https://styled-system.com/responsive-styles

**Comment by eshevlyakova** [comment]
@TFK70 
> добавить в theme кастомный брейкпоинт

Не могу понять как это сделать. Добавить файл breakpoints.ts в ui/theme/src/theme c кодом? 
```typescript
const breakpoints = ['40em']

breakpoints.sm = breakpoints[0]

export default {
  breakpoints,
}
```
Если да, то как потом применить этот брекпоинт вместе с остальными [к этому параметру](https://github.com/torin-asakura/drum-in/blob/feat/opening-the-rhythm-page/landing/fragments/landing-after-the-course/src/tape/tape.component.tsx#L30)?

**Comment by TFK70** [comment]
@eshevlyakova использовать его можно передав в нужное тебе свойство у элемента объект:

Если у тебя в теме есть `{ breakpoints: { laptop: '1280px' } }` - то ты сможешь его триггернуть так: `width={{ laptop: '100%' }}`

**Comment by eshevlyakova** [comment]
@TFK70 
> width={{ laptop: '100%' }}

А как задать width для всех остальных разрешений (как сейчас width={[100, 200, 300]})?

**Comment by TFK70** [comment]
@eshevlyakova а в чём проблема?

**Comment by eshevlyakova** [comment]
@TFK70 
> а в чём проблема?

Дефолтные брекпоинты пишутся в [], а мой кастомный в {}. Как совместить их в одном параметре?

**Comment by TFK70** [comment]
@eshevlyakova хочешь сказать что массив - это не объект?

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Добавление кастомного брекпоинта

### Описание

Создала файл breakpoints.ts в ui/theme/src/theme и прописала параметру значение, но этот брекпоинт не срабатывает

### Контекст

[Брекпоинт](https://github.com/torin-asakura/drum-in/blob/feat/opening-the-rhythm-page/ui/theme/src/theme/breakpoints.ts)
[Компонент](https://github.com/torin-asakura/drum-in/blob/feat/opening-the-rhythm-page/landing/fragments/landing-after-the-course/src/tape/tape.component.tsx#L30)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Переходим на страницу "Открытие ритма" (через выдвигающееся меню)
3. Скролим до секции "После курса", выбираем элемент элемент, которому задан параметр с кастомным брекпоинтом, и видим что брекпоинт не отображается

### Ожидаемое поведение

Брекпоинт срабатывает с 1280px и дефолтные брекпоинты также работают

### Вопрос

1. В чем ошибка?
2. И правильно ли я [задала значения](https://github.com/torin-asakura/drum-in/blob/feat/opening-the-rhythm-page/landing/fragments/landing-after-the-course/src/tape/tape.component.tsx#L30) для дефолтных брекпоинтов?

**Comment by TFK70** [comment]
@eshevlyakova 

> И правильно ли я [задала значения](https://github.com/torin-asakura/drum-in/blob/feat/opening-the-rhythm-page/landing/fragments/landing-after-the-course/src/tape/tape.component.tsx#L30) для дефолтных брекпоинтов?

Да, тут всё правильно

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/54
