### ISSUE TITLE
Program - Страница "Ощущение времени"

### ISSUE THREAD

**Issue by eshevlyakova** [torin-asakura/drum-in#56]
### Задача
Сделать фрагмент [program](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1303%3A10432&t=J2wYU6dcRqnnV7Yv-4)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 [Эта секция](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1303%3A10432&t=yNA9liAl2Q4MtydC-4) должна прокручиваться по ширине при обычном (вертикальном) скролле страницы?

**Comment by TFK70** [comment]
@eshevlyakova узнай у дизайнера, можешь сразу ему такие вопросы адресовывать

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Создание горизонтальной секции

### Описание

Не понимаю как реализовать этот блок, а именно, чтобы при обычной прокрутки, контент секции горизонтально прокручивался 

### Контекст

[Секция в дизайне](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1303%3A10432&t=mEJEbK8XbNOrlNXa-4)

### Ожидаемое поведение

При обычном скролле секция прокручивается по горизонтали

### Действия

1. Гуглила, [нашла такой вариант,](https://stackoverflow.com/questions/60419944/horizontal-scrolling-sticky-section/60627759#60627759:~:text=space%20holder%20%2D%20This,that%20it%20contains.) но не до конца знаю, как перенести на react

### Вопрос

1. Подходит вариант, который я нашла, или можно по-другому?

**Comment by TFK70** [comment]
@eshevlyakova это параллакс, здесь не нужно делать скролл по горизонтали
Если пока не хочешь разбираться как это сделать - можешь в [этой](https://github.com/torin-asakura/drum-in/issues/58) задаче оставить отметку

**Comment by eshevlyakova** [comment]
@TFK70 
> Если пока не хочешь разбираться как это сделать

А можешь скинуть примеры или статьи с реализацией?
Можно по этому [примеру](https://stackoverflow.com/questions/60419944/horizontal-scrolling-sticky-section/60627759#60627759:~:text=space%20holder%20-%20This,that%20it%20contains) делать?

**Comment by TFK70** [comment]
@eshevlyakova это можно сделать с помощью как раз locomotive scroll, у них даже на официальном сайте есть параллакс эффект, ровно как тот, который нужно сделать тебе - https://locomotivemtl.github.io/locomotive-scroll/

Мы его пока используем только для "утяжеления" скролла

Насчет статей/примеров не подскажу, можешь погуглить, но по идее документации locomotive scroll должно хватить

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Создание параллакса для секции "Программа"

### Описание

Секция отображается, длина[ блока](https://github.com/torin-asakura/drum-in/blob/feat/feeling-of-time-page/landing/fragments/landing-program-horizontal/src/program-horizontal.component.tsx#L10) (который должен прокручиваться) 3000px, но он не прокручивается горизонтально. Делала по примеру с [сайта ](https://locomotivemtl.github.io/locomotive-scroll/)(с помощью [атрибутов](https://github.com/locomotivemtl/locomotive-scroll/blob/master/docs/index.html#L220))

### Контекст

[Код](https://github.com/torin-asakura/drum-in/blob/feat/feeling-of-time-page/landing/fragments/landing-program-horizontal/src/program-horizontal.component.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Переходим на страницу "Ощущение времени" (через выдвигающееся меню)
3. Скролим до оранжевого цвета (после секции "Этот курс для вас")

### Ожидаемое поведение

При обычном скролле секция прокручивается по горизонтали

### Действия
1. Читала документацию
2. Сравнивала с примером
### Вопрос

1. Из-за чего так и как это исправить?

**Comment by TFK70** [comment]
@eshevlyakova коммитнул, тебе пары атрибутов не хватало

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Создание параллакса для секции "Программа"

### Описание

Мне нужно чтобы при достижении данной секции, она фиксировалась по вертикали и прокручивалась по горизонтали. Но сейчас она во-первых с самого начала прокручивается справа до конца левого края и не фиксируется вертикально. 
На [их сайте](https://locomotivemtl.github.io/locomotive-scroll/) что-то похожее реализовано с помощью margin-bottom, но у них и сами элементы и по горизонтали и по вертикали скроляться. А мне нужно только по горизонтали, а по вертикали height='100vh'

### Контекст

[Код](https://github.com/torin-asakura/drum-in/blob/feat/feeling-of-time-page/landing/fragments/landing-program-horizontal/src/program-horizontal.component.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Переходим на страницу "Ощущение времени" (через выдвигающееся меню)
3. Скролим до оранжевого цвета (после секции "Этот курс для вас")

### Ожидаемое поведение

Когда доходим до этой секции, блок фиксируется по вертикали и мы начинам прокручиваться по ширине, и когда ширина блока закончилась, мы обычным вертикальным скролом листаем остальные секции

### Действия
1. Гуглила
2. Пробывала использовать атрибут data-scroll-sticky

### Вопрос

1. Как это можно реализовать?

**Comment by TFK70** [comment]
@eshevlyakova у блока к которому должны прилепляться твои кубы должен быть display block

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Создание параллакса для секции "Программа"

### Описание

Осталась проблема о которой я писала выше: секция прокручивается не с самого начала (текст "Программа"), а с черного фона и только потом контент секции

### Контекст

[Код](https://github.com/torin-asakura/drum-in/blob/feat/feeling-of-time-page/landing/fragments/landing-program-horizontal/src/program-horizontal.component.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Переходим на страницу "Ощущение времени" (через выдвигающееся меню)
3. Скролим до секции программы (после секции "Этот курс для вас")

### Ожидаемое поведение

Когда доходим до этой секции сразу отображается надпись "Программа" и при скролле появляется остальной контент

### Медиа материалы

Сначала идет черный фон, а уже потом выезжает контент секции:
<img width="1280" alt="Снимок экрана 2023-02-15 в 12 59 07" src="https://user-images.githubusercontent.com/79781486/218995487-4931e54b-af38-4707-bb43-4cce679c0e7d.png">
А должно быть сразу так:
<img width="765" alt="Снимок экрана 2023-02-15 в 13 02 30" src="https://user-images.githubusercontent.com/79781486/218996319-cc5186c7-11e9-41ba-8fa2-ff1f61d50272.png">

### Действия
1. Читала документацию
2. Пробывала задавать absolute [этому блоку](https://github.com/torin-asakura/drum-in/blob/feat/feeling-of-time-page/landing/fragments/landing-program-horizontal/src/program-horizontal.component.tsx#L14)

### Вопрос

1. Почему так и как можно исправить?

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/74
