### ISSUE TITLE
Parallax rework

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/drum-in#58]
## Задача

Реворкнуть параллакс эффект ленты на главной странице

Сейчас для прокрутки используется swiper, но это выглядит топорно, и с технической точки зрения это оверхед

### План:
- [x] При прокрутке страницы прокручивать по горизонтали блок с карточками (с помощью locomotive scroll)
- [x] Инвертировать направление скролла для нижней линии

**Comment by eshevlyakova** [comment]
Параллакс в этой секции: https://github.com/torin-asakura/drum-in/issues/56

**Comment by eshevlyakova** [comment]
@TorinAsakura 
### Скоуп

Создание parallax для блока процесс обучения

### Описание

Составила план, сделала первый пункт. Но нет идей как сделать бесконечную линию с карточками

### Контекст

[Верхняя линия с карточками](https://github.com/torin-asakura/drum-in/blob/fix/parallax-in-learning-process-component/landing/fragments/landing-learning-process/src/slider-top/slider-top.component.tsx#L36-L48)

### Ожидаемое поведение

Ленты двигаются вместе со скроллом страницы

### Действия

1. Гуглила и искала примеры
2. Читала документацию locomotive-scroll

### Вопрос

1. Как можно реализовать бесконечную линию с карточками?

**Comment by TorinAsakura** [comment]
@eshevlyakova Для начала надо определить понятия: что тебе необходимо, с какими осями тебе необходимо работать, по каким координатам что двигать, какая последовательность. Ты неверно ставишь вопрос и уж точно неверно пытаешься его решить. Ты так ничего и никогда не сможешь решить бегая по гуглу в поисках примеров и читаю доку.

**Comment by eshevlyakova** [comment]
@TorinAsakura 
### Скоуп

Создание parallax для блока процесс обучения

### Описание

Сделала первый пункт плана, а именно при достижении блока и скролле страницы - ленты с карточками прокручиваются. Но все в одну сторону. Нужно, чтобы нижняя лента прокручивалась в обратном направлении по отношению к верхней.
Хочу внутри [этого компонента](https://github.com/torin-asakura/drum-in/blob/fix/parallax-in-learning-process-component/landing/fragments/landing-learning-process/src/slider-bottom/slider-bottom.component.tsx#L37) инвертировать скролл (не контент) и по идее locomotive scroll тоже сменит направление, но с помощью чего это сделать не знаю

### Контекст

[Нижняя лента с карточками](https://github.com/torin-asakura/drum-in/blob/fix/parallax-in-learning-process-component/landing/fragments/landing-learning-process/src/slider-bottom/slider-bottom.component.tsx#L37-L54)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Скролим до блока с заголовком "Во время обучения вас ждет"

### Ожидаемое поведение

Лента с карточками двигаются в противоположенном направлении по отношению друг к другу при скролле страницы (когда страница не скроллится блок стоит на месте)

### Действия

1. Искала встроенную возможность инвертировать направление скролла в locomotive-scroll
2. Пробывала применить transform: scaleX(-1)

### Вопрос

1. С помощью чего это можно реализовать?

**Comment by TorinAsakura** [comment]
@eshevlyakova Тебе нужно просто перевернуть массив с объектами, а направление скролла менять не обязательно. С «переворачиванием» массива справишься?
