### ISSUE TITLE
Форма "Разовый платеж"

### ISSUE THREAD

**Issue by eshevlyakova** [torin-asakura/drum-in#63]
### Задача
Сделать фрагмент [форму "Разовый платеж"](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1202%3A10959&t=XNHY7Zgosan6DpJW-4)

- [x] desktop
- [x] mobile

**Comment by eshevlyakova** [comment]
@TFK70 
Я сейчас делаю [табы в форме](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1448%3A11702&t=wpen9C75CJFQf7QF-4) и начала делать по примеру vsble, но тут задействован [хук @apollo/client](https://github.com/torin-asakura/VSBLE/blob/1837a24322665d41b3d75a906f8a46529fe5c7f8/site/fragments/filters/src/artbuyer/artbuyer-filters.component.tsx#L1). Его можно чем-то заменить или найти и использовать другую реализацию (например как в [dream-team](https://github.com/torin-asakura/dream-team/blob/master/ui/form/src/form.component.tsx#L106-L150))?

И также вопрос в [этой форме](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1202%3A10959&t=wpen9C75CJFQf7QF-4) должен меняться текст (к примеру [название курса](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1448%3A11692&t=wpen9C75CJFQf7QF-4)) в зависимости от того, на какой странице она была вызвана?

**Comment by TFK70** [comment]
@eshevlyakova а ты поняла что эти хуки делают?

**Comment by eshevlyakova** [comment]
@TFK70 
> а ты поняла что эти хуки делают?

useReactiveVar читает переменные, и повторно рендерит, если они были изменены

**Comment by TFK70** [comment]
@eshevlyakova 

> useReactiveVar читает переменные, и повторно рендерит, если они были изменены

Тогда заменяй его на равносильный функционал, если у тебя нету общего стора

> И также вопрос в [этой форме](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1202%3A10959&t=wpen9C75CJFQf7QF-4) должен меняться текст (к примеру [название курса](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1448%3A11692&t=wpen9C75CJFQf7QF-4)) в зависимости от того, на какой странице она была вызвана?

Это дизу

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Замена хука и метода из apollo на самописный код

### Описание

Не могу понять как написать функцию которая заменит хук useReactiveVar и метод MakeVar. 
Метод, как я поняла просто объявляет переменную (реактивную). Насчет хука, если он повторно рендрит, то нужно использовать react хук useMemo

### Контекст

[Код](https://github.com/torin-asakura/drum-in/blob/feat/form-and-payment/ui/modal-forms/src/modal-forms.component.tsx#L30-L31)

### Вопрос

1. Как и чем заменить метод MakeVar?

**Comment by eshevlyakova** [comment]
@TFK70 
Я не могу найти в [примере](https://github.com/torin-asakura/VSBLE/blob/1837a24322665d41b3d75a906f8a46529fe5c7f8/site/fragments/filters/src/filters.component.tsx) где подгружается контент таба. К примеру в данном случае, если активен таб "All", то отображаются данные карточки:
<img width="1242" alt="Снимок экрана 2023-01-18 в 20 12 54" src="https://user-images.githubusercontent.com/79781486/213248988-e12f8bac-000f-4dfe-8f13-079f86e7c8eb.png">

Но откуда они отображаются?

**Comment by eshevlyakova** [comment]
@TFK70 
### Скоуп

Контент в зависимости от выбранного таба

### Описание

В переменную roleVar сохраняется по два значения (к примеру по умолчанию там строчка "Рассрочка", но если я нажму на "Разовый платеж", то он вторым элементом добавится в массив), а мне нужно, чтобы в массиве был всегда только один элемент

### Контекст

[Код](https://github.com/torin-asakura/drum-in/blob/feat/form-and-payment/ui/modal-forms/src/modal-forms.component.tsx)

### Действия
1. Изменяла [параметр mutuallyExclusive в options](https://github.com/torin-asakura/drum-in/blob/feat/form-and-payment/ui/modal-forms/src/modal-forms.component.tsx#L40), но тогда модальное окно вовсе не открывалось и в консоль бесконечное количество раз выводилась переменная roleVar. Хотя в [примере](https://github.com/torin-asakura/VSBLE/blob/master/site/fragments/filters/src/filters.component.tsx#L50) для этого параметра стоит true и на сайте все работает

### Вопрос

1. Из-за чего это и как это исправить?

**Comment by TFK70** [comment]
@eshevlyakova кинул фикс

**Comment by eshevlyakova** [comment]
https://github.com/torin-asakura/drum-in/pull/66
