### ISSUE TITLE
Работа с данными

### ISSUE THREAD

**Issue by eshevlyakova** [torin-asakura/drum-in#81]
### Задача

- [x] Почитать про graphql, apollo
- [x] Создать одну запись для курсов и запросить ее через apollo

**Comment by eshevlyakova** [comment]
@TorinAsakura 
### Скоуп

Загрузка данных с graphql

### Описание

У нас несколько одинаковых страниц, но с разным контентом. Я создаю несколько записей, и как эти данные выгружать для каждой страницы? 
Моя идея заключается в том, чтобы сделать функцию helpers и каждой странице выдать id (который соответсвует id определенной записи на wp). А в компоненте (в котором нужно подгрузить к примеру заголовок) создать цикл, пройтись по полученному массиву на соответствие айдишников, если равны, то выгрузить заголовок

### Ожидаемое поведение

Для каждой страницы курса подгружается свой объект с данными из полученного массива

### Вопрос

1. Моя идея реализация корректна или нет? Если нет, то почему?
2. Как писать контент (описание, надписи для tape линии и тд), чтобы получать только текст? А то сейчас есть теги в контенте и в целом весь контент находится в одном свойстве объекта content:
```javascript
"content": "\n<p>Курс, который поможет понимать, исполнять и писать музыку</p>\n",
```

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> ### Скоуп
> Загрузка данных с graphql
> 
> ### Описание
> У нас несколько одинаковых страниц, но с разным контентом. Я создаю несколько записей, и как эти данные выгружать для каждой страницы? Моя идея заключается в том, чтобы сделать функцию helpers и каждой странице выдать id (который соответсвует id определенной записи на wp). А в компоненте (в котором нужно подгрузить к примеру заголовок) создать цикл, пройтись по полученному массиву на соответствие айдишников, если равны, то выгрузить заголовок
> 
> ### Ожидаемое поведение
> Для каждой страницы курса подгружается свой объект с данными из полученного массива
> 
> ### Вопрос
> 1. Моя идея реализация корректна или нет? Если нет, то почему?
> 2. Как писать контент (описание, надписи для tape линии и тд), чтобы получать только текст? А то сейчас есть теги в контенте и в целом весь контент находится в одном свойстве объекта content:
> 
> ```js
> "content": "\n<p>Курс, который поможет понимать, исполнять и писать музыку</p>\n",
> ```

Нет. Однозначно нет.
- Для каждой страницы нужно создавать свой тип записи
- Для каждого блока страницы создаём свою запись
- Если нужно строки текста - иди в "группы полей"
- Для курсов создавай отдельный тип записи, так как курсы могут быть везде, и мы должны иметь возможность запрашивать их вне зависимости от контекста

Чтобы это не было в одной куче - нужно детализировано описывать свои пост-тайпы, фактически, каждый тип записи это ендпойнт
- например тип записи курсы: wp.drumin.pro/graphql/?courses?id=1 и т.д.

**Comment by eshevlyakova** [comment]
@TorinAsakura 
> Для курсов создавай отдельный тип записи, так как курсы могут быть везде, и мы должны иметь возможность запрашивать их вне зависимости от контекста

У нас почти каждая страница курсов отличается одним-двумя блоками друг от друга. Получается для каждой страницы курсов создавать отдельный тип записи?

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> > Для курсов создавай отдельный тип записи, так как курсы могут быть везде, и мы должны иметь возможность запрашивать их вне зависимости от контекста
> 
> У нас почти каждая страница курсов отличается одним-двумя блоками друг от друга. Получается для каждой страницы курсов создавать отдельный тип записи?

Безусловно. Если есть какие-то повторяющиеся куски - делай тип записи fragments - как у нас на клиенте

**Comment by TorinAsakura** [comment]
> 
1. Создаёшь для типа записи "курсы" группу полей, в группе полей создаёшь repeater (повторитель), в нём создаёшь 4 поля, 3 из которых текстовые и 1 с изображением. Любая непонятка - сразу пиши, там можно надолго увязнуть
2. Два варианта: можешь получать картинки напрямую из медифайлов самого вордпресса или же,и да, сделать тип записи slider, добавить туда "Слайдер на главной" и туда тянуть файлики из медиатеки вордпресса. Второй вариант, как по мне, более организованный и правильный

**Comment by eshevlyakova** [comment]
@TorinAsakura 
>  группе полей создаёшь repeater

Так он же только для pro версии

**Comment by TorinAsakura** [comment]
@eshevlyakova А, её там нет? Вот ведь беда. Поставлю тогда чуть позже

**Comment by eshevlyakova** [comment]
@TorinAsakura 
### Скоуп

Загрузка данных для слайдера

### Описание

При запуске сайта появляется ошибка (в консоли нет), не могу понять как ее исправить. Если убираю вызов слайдера, то все работает как нужно. 
Как я поняла что-то пытается обратиться к классам слайдера/слайдов, но их нет (= undefined). Значит нужно сделать проверку на то, что массив с слайдами не пустой и не равен undefined, но не знаю как это правильнее сделать

### Контекст

[Код](https://github.com/torin-asakura/drum-in/blob/feat/uploading-content/landing/fragments/landing-program/src/mobile-list/mobile-list.component.tsx)

### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Переходим на страницу "Открытие ритма" (через выдвигающееся меню)

### Ожидаемое поведение

Сайт запускается без ошибок и данные для слайдера подгружаются

### Медиа материалы

<img width="1280" alt="Снимок экрана 2023-03-15 в 16 39 23" src="https://user-images.githubusercontent.com/79781486/225325882-01182051-7381-4b9e-8a51-161c3a687318.png">

### Вопрос

1. Правильно ли я поняла причину ошибки и как ее исправить? Просто с помощью condition проверять переменную [programOpeningTheRhythmChildren](https://github.com/torin-asakura/drum-in/blob/feat/uploading-content/landing/fragments/landing-program/src/mobile-list/mobile-list.component.tsx#L17)?

**Comment by TorinAsakura** [comment]
@eshevlyakova Прежде чем спрашивать - нужно попробовать. А тут ты не обращаешься за помощью, а, фактически спрашиваешь разрешения проверить гипотезу. Проверяй.

**Comment by eshevlyakova** [comment]
@TorinAsakura 
> [Секция "Учитель"](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1780%3A18115&t=9cgBRGsifja66Hdf-4): получается для загрузки картинок в слайдер я создаю кастомный тип записей, а для загрузки текста (например заголовка, описания) создаю запись в кастомном типе фрагменты (так как этот блок повторяется на всех страницах)?
>> Два варианта: можешь получать картинки напрямую из медифайлов самого вордпресса или же,и да, сделать тип записи slider, добавить туда "Слайдер на главной" и туда тянуть файлики из медиатеки вордпресса. Второй вариант, как по мне, более организованный и правильный

А если у нас есть repeater, то я могу просто создать группу полей, подгружать заголовок, описания и также картинки для слайдера, как раз таки с помощью него?

**Comment by TorinAsakura** [comment]
@eshevlyakova Так с помощью него и нужно было, я же написал

**Comment by eshevlyakova** [comment]
@TorinAsakura 
А header и footer пока не трогать? Потому что, чтобы создать к примеру меню - нужно создавать страницы курсов

**Comment by TorinAsakura** [comment]
@eshevlyakova Почему же? Делай

**Comment by eshevlyakova** [comment]
@TorinAsakura 
Я добавила группу [полей "Уровень курса"](https://wp.drumin.pro/wp-admin/post.php?post=248&action=edit) для каждого [элемента меню "Курсы"](https://wp.drumin.pro/wp-admin/customize.php?return=%2Fwp-admin%2Fpost.php%3Fpost%3D248%26action%3Dedit), но оно не отображается. Почему?

**Comment by TorinAsakura** [comment]
@eshevlyakova Потому что у тебя выбран MenuItem который является системным элементом меню, который, ты, в свою очередь, можешь создать через "внешний вид -> меню"

**Comment by TorinAsakura** [comment]
@eshevlyakova Твой тип должен соответствовать курсам

**Comment by TorinAsakura** [comment]
@eshevlyakova Тебе вообще не нужно никакие меню указывать: меню - это системная сущность вордпресса - мы с ней не работаем. Делай элементы меню также как в обычных своих типах записей. Не трогай ты меню.

**Comment by TorinAsakura** [comment]
@eshevlyakova Для тебя это такие же данные как и все другие. Тебе нужно просто получить от бэкенда свои стринги и распихать их у себя на клиенте. Не используй системные сущности вордпресса.

**Comment by eshevlyakova** [comment]
@TorinAsakura 
А с формами все тоже самое? В плане я просто делаю поля для placeholder инпута и подгружаю их у себя?

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> А с формами все тоже самое: я просто делаю поля для placeholder инпута и подгружаю их у себя? И мне не нужно реализовывать отправку данных формы?

У тебя есть примеры в соседних репах, не задавай пожалуйста вопросов на которые у тебя рядом есть ответы.

**Comment by eshevlyakova** [comment]
@TorinAsakura 

Что это за [тип данных](https://github.com/torin-asakura/dream-team/blob/22799ea7102fcbd1005fb7ecefb1e5c63f522084/ui/form/src/data/queries/submit-form.mutation.ts#L25) с точки зрения wordpress? Я имею ввиду как и где мне создать форму или какой-то кастомный тип, чтобы делать такой же запрос для своей формы?

**Comment by eshevlyakova** [comment]
@TorinAsakura 
> собирается в конструкторе

Что ты имеешь ввиду под словом "конструктор"? Я просто до этого работала с формами и wp только через плагины. И так как у меня есть только пример кода с одной стороны, не очень понятно как это выглядит на wordpress

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> > собирается в конструкторе
> 
> Что ты имеешь ввиду под словом "конструктор"? Я просто до этого работала с формами и wp только через плагины. И так как у меня есть только пример кода с одной стороны, не очень понятно как это выглядит на wordpress

конструктор форм, в твоём случае это contact form 7, в случае с ДТ/Мисик/ШД - ninja forms

**Comment by TorinAsakura** [comment]
@eshevlyakova Возможно поэтому был выбран ниндзя. Ты уверена что для cf7 нет настроек дающих доступ к graphql?

**Comment by TorinAsakura** [comment]
@eshevlyakova Пока да, сейчас сам зайду посмотрю, чо там да как

**Comment by eshevlyakova** [comment]
@TorinAsakura 
Я так понимаю для связки ninja forms и graplQL вы используете это: https://github.com/toriphes/wp-graphql-ninja-forms?

**Comment by TorinAsakura** [comment]
@eshevlyakova Именно так. На каждый плагин (если разрабы не позаботились о доступности) есть плагин для доступа к граУ

**Comment by eshevlyakova** [comment]
@TorinAsakura 

Как только активирую WPGraphQL Ninja Forms плагин пропадают все поля в GraphiQL:

<img width="1000" alt="Снимок экрана 2023-03-20 в 17 28 29" src="https://user-images.githubusercontent.com/79781486/226370768-08110981-143b-4d47-99fa-6d32aa750b6c.png">

**Comment by eshevlyakova** [comment]
@TorinAsakura Капча для сайта

**Comment by TorinAsakura** [comment]
> @TorinAsakura Капча для сайта

Done

**Comment by eshevlyakova** [comment]
@TorinAsakura 

При запуске сайта капча пишет, что неверный ключ. Делала по примеру (копировала ключ из поля reCAPTCHA v3 Site Key)

<img width="294" alt="Снимок экрана 2023-04-03 в 11 57 18" src="https://user-images.githubusercontent.com/79781486/229461707-fc74cc59-e247-4dcb-99e2-ed2633167a4f.png">

**Comment by TorinAsakura** [comment]
site: 6LeivSwlAAAAAL1abQj0DBd-w7zVtCHFHGge_Z7S
secret: 6LeivSwlAAAAAMfVjNg9y8PGUETMVrICL90y3iSL

**Comment by eshevlyakova** [comment]
@TorinAsakura 

> site: 6LeivSwlAAAAAL1abQj0DBd-w7zVtCHFHGge_Z7S

Я этот ключ и использовала. А это 3 версия капчи?

**Comment by eshevlyakova** [comment]
@TorinAsakura 

> Да, третья

Можно поставить вторую? Потому что библиотека которая используются на наших сайтах ([react-google-recaptcha](https://www.npmjs.com/package/react-google-recaptcha)) поддерживает 2 версию. 
В крайнем случае буду искать для 3 версии

**Comment by TorinAsakura** [comment]
@eshevlyakova То есть в крайнем? Ищи для третьей конечно же.

**Comment by eshevlyakova** [comment]
@TorinAsakura 
### Скоуп

Использование библиотеки React Google Recaptcha V3

### Описание

По умолчанию все работает, но капча отображается под модальным окном и рендерится с помощью iframe глобально. Мне нужно, что капча была внутри дива. Я могу это сделать с помощью [пропса container.element](https://github.com/t49tran/react-google-recaptcha-v3#googlerecaptchaprovider). Туда я передаю строку с id нужного Box, но при открытии модального окна с капчей появляется ошибка (скрины)

### Контекст

[Компонент GoogleReCaptchaProvider](https://github.com/torin-asakura/drum-in/blob/feat/uploading-content/ui/form/src/form.component.tsx#L104-L110)
[Box с id](https://github.com/torin-asakura/drum-in/blob/feat/uploading-content/ui/form/src/form.component.tsx#L178)


### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/renderer-entrypoint run dev`
2. Нажимаем на кнопку "Связаться" в шапке

### Ожидаемое поведение

Капча работает и отображается внутри дива с нужным id

### Медиа материалы

<img width="861" alt="Снимок экрана 2023-04-03 в 18 39 27" src="https://user-images.githubusercontent.com/79781486/229559205-33331c34-cfd0-471c-8ef4-508285d83e1f.png">

<img width="861" alt="Снимок экрана 2023-04-03 в 18 40 05" src="https://user-images.githubusercontent.com/79781486/229559326-81b42b13-707c-4ec5-94ae-60a85729a1d3.png">

### Вопрос

1. Из-за чего и как это исправить?

**Comment by TorinAsakura** [comment]
@eshevlyakova что-то я ничего не понимаю…что "из-за чего"? Кто с кодом работает я или ты? Где отладочная информация? Почему я не вижу ни одного вывода из console.log? Если он говорит, что видит неверный ключ - значит никакого коннекта к google recaptcha скорее всего не произошло…

ну, давай рассуждать логически:
- нам сообщают что не подходит ключ или не подключено api
- ключ я тебе предоставил из админки, нам известно, что он валидный
- значит не произошло подключение к api

почему так произошло?
- ну тут вариантов как таковых нет, он один - твоя библиотека не подключилась к google recaptcha и это и первокласснику будет понятно, тем более, что такие кейсы ты уже решала ранее
- что касается первой ошибки - посмотри в каком состоянии прилетает плейсхолдер на момент маунта, элементарней и проще кейса по-моему не придумать

Итого:
- ни одной видимой попытки на отладку
- ключ сайта ты тупо кидаешь в переменной, хотя должна получать и передавать его из ninja forms, где он, в общем-то и был введён
- ещё один день потерян без какого-либо результата
- бестолковая беготня по библиотекам пытаюсь обрабатывать библиотеку без поключения к бэкенду Wordpress'a

Очень плохо.

**Comment by eshevlyakova** [comment]
@TorinAsakura 

> твоя библиотека не подключилась к google recaptcha 

То есть как только я добавляю пропс [container](https://github.com/torin-asakura/drum-in/blob/feat/uploading-content/ui/form/src/form.component.tsx#L104) библиотека перестает подключатся к google recaptcha. Но я так и не поняла, как это исправить?

**Comment by eshevlyakova** [comment]
@TorinAsakura 

1. Где должна находиться капча в форме: после кнопки [оставить заявку](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1448-12040&t=I6waeni4SRb9gUqF-4)? И чексбокс "Даю согласие на обработку персональных данных" мы оставляем?
2. Как запустить капчу на localhost для проверки правильной работы формы? (Она просто пишет: Домен localhost не входит в список поддерживаемых)

**Comment by vodopmi** [comment]
> @TorinAsakura
> 
> 1. Где должна находиться капча в форме: после кнопки [оставить заявку](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1448-12040&t=I6waeni4SRb9gUqF-4)? И чексбокс "Даю согласие на обработку персональных данных" мы оставляем?
> 2. Как запустить капчу на localhost для проверки правильной работы формы? (Она просто пишет: Домен localhost не входит в список поддерживаемых)

- в чём вопрос с капчей? где её показать? думаю, нужно делать после нажатия кнопки оверлей классический и по центру капчу
- почему чекбокса не должно быть?

**Comment by TorinAsakura** [comment]
@eshevlyakova 1. А к чему вопрос? Это кастомный элемент или что? Ты никогда капчу нигде не заполняла? Зачем тебе трогать чекбокс? Вообще муть какая-то

**Comment by TorinAsakura** [comment]
@eshevlyakova Не надо. Тогда локально через конст продолжай определять.
