### ISSUE TITLE
opengraph, битые ссылки и прочие прелести последнего релиза

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/drum-in#92]
### Описание бага

- [x] кнопка-скроллер, на главной, - "выбрать курс" не работает (@Nelfimov)
- [x] ВЫБЕРЕТЕ СВОЙ КУРС - грамматическая ошибка (@eshevlyakova)
- [x] кнопки на карточках курсов не работают (@eshevlyakova)
- [x] у кнопки "вверх" отсутствуют рабочие грани, чтобы на неё нажать нужно прицелиться по центру или около того (@eshevlyakova)
- [x] у элементов меню нет состояний (@Nelfimov )
- [x] ссылки в меню в футере имеют target=_blank, хотя не понятно для чего и зачем (@eshevlyakova)
- [x] нет страницы "политика обработки персональных данных" (@eshevlyakova)
- [x] нет страницы "договор оферты" (@eshevlyakova)
- [x] внутри курсов не работает кнопка "начать обучение" (@eshevlyakova)
- [x] #117
- [x] нет favicon (@eshevlyakova)
- [x] нет состояния у иконки включения звука в хедере (@eshevlyakova)
- [x] шрифты (@eshevlyakova)
- [x] в секции курсов на главной не работает горизонтальный скролл (@eshevlyakova)

В целом, надо пройтись по консоли

### Воспроизведение

Актуальный релиз

### Ожидаемое поведение

-

### Материалы

- https://github.com/torin-asakura/misik/blob/master/landing/pages/index-page/src/seo.component.tsx

### Данные окружения

- macOS@13.3.1 (22E261)
- safari@16.4 (18615.1.26.11.23)

**Comment by vodopmi** [comment]
### Описание бага

- [ ] hero не подстраивается под viewport

### Ожидаемое поведение

<img width="1194" alt="Screenshot 2023-04-18 at 17 46 14" src="https://user-images.githubusercontent.com/102182195/232798652-738234cf-b989-4d2f-a538-eaea3d5447f5.png">

**Comment by vodopmi** [comment]
@eshevlyakova 
в секции курсов на главной:
- [ ] не работает горизонтальный скролл 
- [ ] даже перетаскиванием нельзя долистать до конца

это всё в сумме даёт гадкий пользовательский опыт

видео – https://t.me/c/1057842456/37704

**Comment by vodopmi** [comment]
> @eshevlyakova в секции курсов на главной:
> 
> * [x]  не работает горизонтальный скролл
> * [ ]  даже перетаскиванием нельзя долистать до конца
> 
> видео – https://t.me/c/1057842456/37704

@eshevlyakova пример горизонального скролла – 

https://user-images.githubusercontent.com/102182195/234975518-b130ff6c-4702-4174-84d3-c1ba3c95a6ae.mov

**Comment by TorinAsakura** [comment]
@eshevlyakova @vodopmi посмотри иконку пожалуйста

@eshevlyakova это на нашей стороне, обложка для страницы и метатеги, реализуется через helmet

**Comment by vodopmi** [comment]
@TorinAsakura в фигме действительно два состояния. initial и active, в задаче речь про отсутствующий ховер?

**Comment by TorinAsakura** [comment]
@vodopmi Да

**Comment by vodopmi** [comment]
> @TorinAsakura
> 
> > нет настроек для opengraph
> 
> А где эта настройка выполняется: на wp или в коде?
> 
> > нет состояния у иконки включения звука в хедере
> 
> Так в дизайне было всего 2 состояния (разные иконки на паузе и плей), я их и сделала

@eshevlyakova добавил ховеров https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=838%3A3281&t=pgvotgzhRweqAnXn-1

**Comment by eshevlyakova** [comment]
@vodopmi 

> нет настроек для opengraph

Для настройки мне нужна картинка main-cover. К примеру на dream-team она выглядит так:
![Снимок экрана 2023-04-28 в 18 57 28](https://user-images.githubusercontent.com/79781486/235196262-e358cf6c-15c0-48fc-bc5b-d18833b5d64f.png)

**Comment by eshevlyakova** [comment]
@vodopmi 

> нужны ещё какие-нибудь картинки для opengraph? или одна только?

Пока только одна

**Comment by vodopmi** [comment]
> @vodopmi
> 
> > нужны ещё какие-нибудь картинки для opengraph? или одна только?
> 
> Пока только одна

@eshevlyakova извини, отвлёкся и забыл. тегай, пожалуйста, в таких ситуациях.

Пожалуйста, обложка –> [OG-Cover](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=3870%3A16453&t=MtDczuyT0RXVtYKJ-1)

**Comment by vodopmi** [comment]
по админке WP изменения:
- добавил в страницах seo-разметку
- почистил от устаревшего фронта
- добавил альты изображениям

**Comment by TorinAsakura** [comment]
@Nelfimov @vodopmi скооперируйтесь сегодня для реструктуризации проекта

**Comment by vodopmi** [comment]
@Nelfimov по горизонтальному скроллу записал тебе два видео. скролл работает хорошо, но сама секция работает неправильно
- [как должно быть](https://www.loom.com/share/d72778fd0e2d4c21a528b84c7d6ff261)
- [как есть](https://www.loom.com/share/198f3720bc8d4db9908597ae4771ebd8)

**Comment by kalininatonya** [comment]
#112

**Comment by kalininatonya** [comment]
Какие задачи выполнял вчера?
Поправила часть:

- https://github.com/torin-asakura/drum-in/issues/92

Какие задачи будешь делать сегодня?
Исправляю вторую часть:

- https://github.com/torin-asakura/drum-in/issues/92
